'use strict';
// Authored release content for RakenOS generations 1–19.
// Each generation describes its .0.0 feature release in detail, plus the
// authored follow-ups that ship in .0.1 (stability) and .0.2 (polish/security).
// "Section|Text" strings are split by the generator. `subjects` are short noun
// phrases naming what the generation introduced; the generator uses them to
// write targeted maintenance notes for .0.1 and .0.2.

module.exports = [
  {
    major: 1,
    title: 'Initial Release',
    summary: 'RakenOS 1.0.0 is the first public release of RakenOS and establishes the foundation of the entire operating system: the Home Screen, Lock Screen, notifications, Control Center, Raken Store and the first version of the RakenOS Runtime.',
    notes: [
      'Home Screen|Introduces RakenOS Home with a responsive app grid, a dock, widgets and fast access to every installed app.',
      'Home Screen|The Home Screen layout automatically adapts spacing and the number of columns to the size of the display.',
      'Lock Screen|A new Lock Screen with clock, date, notifications, battery status and quick shortcuts.',
      'Lock Screen|PIN protection with a numeric keypad, progressive lockout after repeated incorrect attempts and a separate emergency information view.',
      'Control Center|Introduces quick controls for connectivity, brightness, volume, flashlight and Do Not Disturb.',
      'Notifications|Introduces the RakenOS Notification Center with grouped notifications and individual actions.',
      'Raken Store|Introduces Raken Store with Discover, Search, Categories and a personal Library.',
      'Raken Store|First-class support for RAS (Raken App Software) packages, including manifest validation and signature checks before installation.',
      'Camera|Introduces Camera with photo capture, a composition grid and automatic flash on supported hardware.',
      'Files|Introduces Files with Documents, Downloads and Pictures locations and basic file management.',
      'Settings|Introduces Settings with Display, Sound, Battery, Security, Privacy and System Update.',
      'System|First version of the RakenOS Runtime, including app lifecycle, navigation, system services and hardware capability detection.',
      'RAS Runtime|RAS API level 1 with sandboxed storage, notifications and clock services.',
      'RScript|Introduces RScript 1.0, the scripting language used by RAS applications.',
    ],
    subjects: ['the app grid', 'the dock', 'the Lock Screen keypad', 'the Notification Center', 'Raken Store installations', 'the RAS package validator'],
    s1: 'The first maintenance update to RakenOS improves stability and fixes several issues that were discovered after the release of 1.0.0.',
    f1: [
      'Home Screen|Improved touch response when apps are moved on the Home Screen.',
      'Home Screen|Fixed an issue where the dock could be rendered with the wrong height after rotation.',
      'Notifications|Improved grouping of multiple notifications from the same app.',
      'Battery|Reduced background activity for several system components.',
      'System|Improved memory management when switching quickly between apps.',
    ],
    s2: 'RakenOS 1.0.2 focuses on polish, security and reliability.',
    f2: [
      'Security|Improved validation of installed RAS packages.',
      'Raken Store|Clearer error message when an installation is cancelled because of a corrupt package.',
      'Accessibility|Improved keyboard navigation and clearer focus indicators.',
      'Performance|Shorter time between unlocking and a fully rendered Home Screen.',
    ],
  },
  {
    major: 2,
    title: 'Files, Sharing and Albums',
    summary: 'RakenOS 2 makes it easier to organise and share content. Files gains tags and a new share sheet, Gallery introduces albums, and RAS apps receive scoped storage access so they only see the files you choose.',
    notes: [
      'New|A system-wide share sheet lets you send photos, notes and files to any app that registers as a share target.',
      'Files|Colour tags can be added to any file or folder, and each tag has its own location in the sidebar.',
      'Files|Recent items now appear at the top of Files, grouped by today, yesterday and earlier this week.',
      'Gallery|Introduces albums. Photos can belong to several albums without being duplicated on storage.',
      'Gallery|A new Favourites album collects every photo you mark with the heart button.',
      'Notes|Notes can be exported as plain text files directly into Files.',
      'Privacy|Scoped storage for RAS apps: an app can only open files you pick in the document picker, not your entire storage.',
      'RAS Runtime|RAS API level 2 adds the share-target and document-picker interfaces.',
      'RScript|RScript 1.1 adds map literals and the `for key, value in map` loop form.',
    ],
    subjects: ['the share sheet', 'file tags', 'Gallery albums', 'the document picker', 'scoped storage'],
    s1: 'RakenOS 2.0.1 resolves issues reported with the new share sheet and improves the reliability of albums.',
    f1: [
      'Gallery|Fixed an issue where an album cover could show a photo that had already been deleted.',
      'Files|Renaming a tagged file no longer removes its tags.',
    ],
    s2: 'RakenOS 2.0.2 refines sharing and tightens storage permissions.',
    f2: [
      'Privacy|Apps that were granted access to a single file can no longer list the contents of its parent folder.',
      'Files|Tag colours now have sufficient contrast in both light and dark mode.',
    ],
  },
  {
    major: 3,
    title: 'Notifications, Refined',
    summary: 'RakenOS 3 rebuilds how notifications reach you. Notifications get priorities, Do Not Disturb can follow a schedule, and the Lock Screen can hide sensitive content until the device is unlocked.',
    notes: [
      'Notifications|Notifications now have three priorities: Time-sensitive, Standard and Quiet. Quiet notifications are delivered silently to the Notification Center.',
      'Notifications|Swipe a notification to the left to snooze it for 1 hour, until this evening or until tomorrow morning.',
      'Control Center|Do Not Disturb can now run on a schedule, for example every night between 22:30 and 07:00.',
      'Control Center|Long-press the Do Not Disturb tile to choose a duration without opening Settings.',
      'Lock Screen|New notification privacy option: show content always, only when unlocked, or never.',
      'Lock Screen|Charging information shows the estimated time until the battery is full.',
      'Settings|A new Notifications page lists every app with its own delivery, sound and badge settings.',
      'RAS Runtime|RAS API level 3 lets apps declare notification priorities and actionable buttons.',
    ],
    subjects: ['notification priorities', 'notification snoozing', 'the Do Not Disturb schedule', 'Lock Screen notification privacy'],
    s1: 'RakenOS 3.0.1 improves the reliability of scheduled Do Not Disturb and snoozed notifications.',
    f1: [
      'Notifications|Snoozed notifications now reappear at the correct time after the device has been restarted.',
      'Control Center|Fixed an issue where a Do Not Disturb schedule that crossed midnight ended one day early.',
    ],
    s2: 'RakenOS 3.0.2 polishes notification behaviour and includes important security fixes.',
    f2: [
      'Lock Screen|Notification previews now stay hidden in the app switcher while the device is locked.',
      'Notifications|Time-sensitive notifications from the same app are no longer collapsed into a single group.',
    ],
  },
  {
    major: 4,
    title: 'Camera and Gallery',
    summary: 'RakenOS 4 is a major step forward for photography. Camera captures with HDR and burst, and Gallery gains a complete non-destructive photo editor.',
    notes: [
      'Camera|HDR capture combines several exposures to preserve detail in bright skies and dark shadows.',
      'Camera|Press and hold the shutter button to capture a burst. Gallery groups burst photos into a single stack.',
      'Camera|A level indicator appears when the grid is enabled and the device is held almost horizontally.',
      'Camera|Advanced camera hardware exposes a dedicated zoom control with fixed focal-length stops.',
      'Gallery|A new photo editor with crop, straighten, rotate, exposure, contrast, warmth and saturation.',
      'Gallery|All edits are non-destructive. Choose Revert to Original at any time.',
      'Gallery|Photos can be sorted by date taken or date added, and grouped by day, month or year.',
      'Performance|Camera starts up to 40% faster from the Lock Screen shortcut.',
    ],
    subjects: ['HDR capture', 'burst stacks', 'the photo editor', 'the camera level indicator'],
    s1: 'RakenOS 4.0.1 improves image quality and fixes issues in the new photo editor.',
    f1: [
      'Camera|Improved white balance in HDR photos taken under mixed indoor lighting.',
      'Gallery|Fixed an issue where the crop handles could disappear when zooming into a photo.',
    ],
    s2: 'RakenOS 4.0.2 fine-tunes Camera and Gallery and improves security.',
    f2: [
      'Gallery|Edited photos now export with their original date and time preserved.',
      'Camera|The shutter sound respects the system silent mode where regional rules allow it.',
    ],
  },
  {
    major: 5,
    title: 'Privacy Foundations',
    summary: 'RakenOS 5 puts you in control of what apps can access. A new Privacy dashboard, one-time permissions and live indicators make every sensitive access visible.',
    notes: [
      'Privacy|The Privacy dashboard shows which apps accessed the camera, microphone, location and files during the last 7 days.',
      'Privacy|One-time permissions: grant access only while the app is open. The permission is revoked when you leave the app.',
      'Privacy|A camera or microphone indicator appears in the status bar whenever either is in use.',
      'Privacy|Permissions of apps you have not opened for 60 days are automatically reset.',
      'Control Center|Tap the privacy indicator in Control Center to see which app is using the camera or microphone.',
      'Security|The Security status in Settings now summarises screen lock, package verification and update status.',
      'RAS Runtime|RAS API level 5 introduces runtime permission requests with a system-provided rationale sheet.',
      'Developer APIs|Apps can check whether a permission was granted permanently, once, or denied.',
    ],
    subjects: ['the Privacy dashboard', 'one-time permissions', 'the privacy indicator', 'automatic permission reset'],
    s1: 'RakenOS 5.0.1 resolves several issues with the new permission system.',
    f1: [
      'Privacy|Fixed an issue where a one-time permission could persist if the app was closed from Recent Apps.',
      'Privacy|The Privacy dashboard now shows accesses that happened while the device was locked.',
    ],
    s2: 'RakenOS 5.0.2 strengthens privacy protections and improves the permission prompts.',
    f2: [
      'Privacy|Permission rationale sheets can no longer be displayed on top of another app.',
      'Accessibility|Permission prompts announce the requesting app name first when a screen reader is enabled.',
    ],
  },
  {
    major: 6,
    title: 'Store and Automatic App Updates',
    summary: 'RakenOS 6 introduces automatic updates for RAS apps, delta packages that download only what has changed, and ratings and reviews in Raken Store.',
    notes: [
      'Raken Store|RAS apps can now update automatically in the background while the device is charging.',
      'Raken Store|Delta packages download only the changed files of an app update, typically reducing update size by 60–80%.',
      'Raken Store|Ratings and written reviews appear on app pages, with the most helpful reviews shown first.',
      'Raken Store|The Library shows pending updates, the date of the last update and a full version history for each app.',
      'Security|Each delta package is verified against the signature of the complete resulting package before it is applied.',
      'Settings|New App Updates page: update automatically, only on Wi-Fi, or ask before updating.',
      'RAS Runtime|RAS API level 6 adds an update-completed event so apps can migrate their data after an update.',
    ],
    subjects: ['automatic app updates', 'delta packages', 'Store reviews', 'the Library update list'],
    s1: 'RakenOS 6.0.1 improves automatic app updates and the reliability of delta packages.',
    f1: [
      'Raken Store|Fixed an issue where an app could be updated while it was open in the foreground.',
      'Raken Store|Delta packages now fall back to a full download if the installed app has been modified.',
    ],
    s2: 'RakenOS 6.0.2 polishes the Store and hardens package handling.',
    f2: [
      'Raken Store|Review text now wraps correctly when the system text size is set to its largest value.',
      'Security|Store downloads now resume from the last verified block after a network interruption.',
    ],
  },
  {
    major: 7,
    title: 'Battery Intelligence',
    summary: 'RakenOS 7 learns how you use your device to make the battery last longer. Adaptive Battery, per-app usage statistics and Optimised Charging all arrive in this release.',
    notes: [
      'Battery|Adaptive Battery limits background activity of apps you rarely use, based on usage patterns measured on the device.',
      'Battery|A new usage chart shows battery level and screen-on time for the last 24 hours and the last 10 days.',
      'Battery|Per-app battery usage separates foreground, background and system activity.',
      'Battery|Optimised Charging holds the battery at 80% and completes charging shortly before you usually unplug.',
      'Battery|Battery Saver can now switch on automatically at 10%, 15% or 20%.',
      'Control Center|The Battery Saver tile shows the estimated remaining time when enabled.',
      'Privacy|All usage patterns used by Adaptive Battery stay on the device and are never uploaded.',
      'System|The job scheduler batches network requests from background tasks to reduce radio wake-ups.',
    ],
    subjects: ['Adaptive Battery', 'the battery usage chart', 'Optimised Charging', 'Battery Saver scheduling'],
    s1: 'RakenOS 7.0.1 improves the accuracy of battery statistics and fixes Adaptive Battery issues.',
    f1: [
      'Battery|Improved accuracy of the remaining-time estimate during the first days after an update.',
      'Battery|Fixed an issue where Optimised Charging could stop at 80% when the device was charged at irregular times.',
    ],
    s2: 'RakenOS 7.0.2 refines power management and includes security improvements.',
    f2: [
      'Battery|Apps playing audio in the background are no longer restricted by Adaptive Battery.',
      'Settings|The battery chart now shows periods when Battery Saver was active.',
    ],
  },
  {
    major: 8,
    title: 'Connectivity',
    summary: 'RakenOS 8 improves every connection your device makes. Raken Beam transfers files between nearby RakenOS devices, NFC tag reading arrives on supported hardware, and Wi-Fi roaming is significantly faster.',
    notes: [
      'New|Raken Beam sends photos, files and links to nearby RakenOS devices without an internet connection.',
      'Connectivity|Faster Wi-Fi roaming when moving between access points in the same network.',
      'Connectivity|Saved Wi-Fi networks can be shared with a QR code from the network details page.',
      'Connectivity|On devices with NFC hardware, RakenOS can read NDEF tags and open the matching app or link.',
      'Control Center|Long-press the Wi-Fi or Bluetooth tile to choose a network or accessory directly.',
      'Settings|NFC settings appear automatically on devices where NFC hardware is detected.',
      'RAS Runtime|RAS API level 8 adds a network-state API and an NFC tag API that is only available when the hardware supports it.',
      'Developer APIs|Apps can declare `nfc` as an optional capability and adapt their interface when it is missing.',
    ],
    subjects: ['Raken Beam', 'Wi-Fi roaming', 'NFC tag reading', 'Wi-Fi QR sharing'],
    s1: 'RakenOS 8.0.1 improves the reliability of Raken Beam and wireless connections.',
    f1: [
      'Connectivity|Raken Beam transfers no longer stall when the receiving device turns its screen off.',
      'Connectivity|Fixed an issue where a hidden Wi-Fi network could not be reconnected after a restart.',
    ],
    s2: 'RakenOS 8.0.2 polishes connectivity features and includes security fixes.',
    f2: [
      'Security|Raken Beam now requires confirmation on the receiving device before any file is written.',
      'Connectivity|NFC tags containing only a URL now show the full address before it is opened.',
    ],
  },
  {
    major: 9,
    title: 'Performance Foundation',
    summary: 'RakenOS 9 rebuilds core parts of the system for speed. A new compositor, preloading of frequently used apps and a caching RScript interpreter make the whole system feel more responsive.',
    notes: [
      'Performance|A new system compositor renders the Home Screen, Control Center and app transitions in a single pass.',
      'Performance|Frequently used apps are preloaded in the background when memory allows, making cold starts up to 35% faster.',
      'Performance|Settings search now returns results instantly from a local index.',
      'RScript|RScript 1.8 caches parsed scripts, so RAS apps start faster from the second launch onwards.',
      'System|Low-memory handling now closes background apps in order of least recent use instead of largest size.',
      'Battery|The new compositor reduces power consumption during scrolling by avoiding redundant redraws.',
      'Developer APIs|A new performance overlay in Developer options shows frame times and dropped frames.',
    ],
    subjects: ['the new compositor', 'app preloading', 'the RScript parse cache', 'the performance overlay'],
    s1: 'RakenOS 9.0.1 resolves issues introduced by the new compositor.',
    f1: [
      'Performance|Fixed occasional flicker when Control Center was opened during an app transition.',
      'RScript|The parse cache is now invalidated correctly after a RAS app is updated.',
    ],
    s2: 'RakenOS 9.0.2 completes the performance work of RakenOS 9 with further polish and security fixes.',
    f2: [
      'Performance|App preloading is paused while Battery Saver is active.',
      'System|Improved recovery from a stalled system service without restarting the device.',
    ],
  },
  {
    major: 10,
    title: 'Multitasking',
    summary: 'RakenOS 10 introduces a new way to work with several apps. Split View shows two apps side by side, and the redesigned Recent Apps lets you save and reopen app pairs.',
    notes: [
      'New|Split View shows two apps on screen at once. Drag the divider to resize them.',
      'New|App pairs: save two apps you often use together and reopen them as a single item from Recent Apps.',
      'Home Screen|Recent Apps has been redesigned with larger previews and a clear-all button that is always reachable.',
      'Home Screen|Swipe left or right along the gesture bar to switch between the most recent apps.',
      'System|Apps now receive a lifecycle event when they move between full screen and Split View.',
      'Accessibility|Split View can be controlled entirely with a hardware keyboard.',
      'RAS Runtime|RAS API level 10 adds responsive layout breakpoints to RDesign so apps adapt to Split View.',
      'Developer APIs|RDesign layouts can define compact and regular variants that switch automatically.',
    ],
    subjects: ['Split View', 'app pairs', 'the redesigned Recent Apps', 'gesture bar app switching'],
    s1: 'RakenOS 10.0.1 improves Split View stability and fixes issues in Recent Apps.',
    f1: [
      'Home Screen|Fixed an issue where an app pair could open with the divider in the wrong position.',
      'System|Apps in Split View now keep their state after the device is locked and unlocked.',
    ],
    s2: 'RakenOS 10.0.2 polishes multitasking and includes security updates.',
    f2: [
      'Home Screen|The Split View divider is easier to grab and shows a subtle handle while dragging.',
      'Accessibility|Screen readers now announce which side of Split View has focus.',
    ],
  },
  {
    major: 11,
    title: 'Interactive Widgets',
    summary: 'RakenOS 11 makes widgets truly useful. Widgets become interactive, can be combined into stacks, and RAS developers can build their own widgets for the first time.',
    notes: [
      'Home Screen|Widgets are now interactive. Tick off a checklist item, start a timer or toggle a setting without opening the app.',
      'Home Screen|Widget stacks combine several widgets in the same space. Swipe vertically to move between them.',
      'Home Screen|Smart Rotate shows the most relevant widget in a stack based on the time of day.',
      'Home Screen|New widget gallery with previews in every available size.',
      'Lock Screen|The Clock and Battery widgets can be shown below the time on the Lock Screen.',
      'RAS Runtime|RAS API level 11 introduces the widget API with small, medium and large sizes.',
      'RDesign|Widgets are described in RDesign and rendered by the system for consistent spacing and typography.',
      'Developer APIs|Widget timelines let apps schedule content updates without running in the background.',
    ],
    subjects: ['interactive widgets', 'widget stacks', 'Smart Rotate', 'the widget gallery'],
    s1: 'RakenOS 11.0.1 improves widget reliability.',
    f1: [
      'Home Screen|Fixed an issue where an interactive widget could briefly show outdated content after a tap.',
      'Home Screen|Widget stacks no longer rotate while you are editing the Home Screen.',
    ],
    s2: 'RakenOS 11.0.2 polishes widgets and includes security updates.',
    f2: [
      'Home Screen|Widgets now use the correct corner radius on displays with rounded corners.',
      'Battery|Widget timeline updates are batched while the display is off.',
    ],
  },
  {
    major: 12,
    title: 'Accessibility for Everyone',
    summary: 'RakenOS 12 is the largest accessibility release so far. Raken Narrator, a full-screen magnifier, colour filters and much larger text sizes make RakenOS usable for more people.',
    notes: [
      'Accessibility|Raken Narrator is a new built-in screen reader with touch exploration, rotor navigation and adjustable speech rate.',
      'Accessibility|Magnifier zooms the entire screen up to 8× with a three-finger double tap.',
      'Accessibility|Colour filters for protanopia, deuteranopia and tritanopia, plus a greyscale mode.',
      'Accessibility|Text size can now be increased up to 200% and every system app reflows its layout accordingly.',
      'Accessibility|Reduce Motion replaces sliding transitions with cross-fades throughout the system.',
      'Settings|The Accessibility page is reorganised into Vision, Hearing, Motor and General sections.',
      'RAS Runtime|RAS API level 12 exposes accessibility labels, roles and hints for every RDesign component.',
      'RDesign|RDesign validates that interactive components have labels and warns developers during packaging.',
    ],
    subjects: ['Raken Narrator', 'the Magnifier', 'colour filters', 'Reduce Motion'],
    s1: 'RakenOS 12.0.1 improves Raken Narrator and fixes accessibility issues across the system.',
    f1: [
      'Accessibility|Raken Narrator no longer reads the same notification twice when it arrives while the screen is off.',
      'Accessibility|Fixed an issue where Magnifier could lose track of the text cursor in Notes.',
    ],
    s2: 'RakenOS 12.0.2 continues the accessibility work with polish and security improvements.',
    f2: [
      'Accessibility|Colour filters are now applied to screenshots only when you choose to include them.',
      'Accessibility|Raken Narrator announces progress while a system update is downloading.',
    ],
  },
  {
    major: 13,
    title: 'Store Discovery',
    summary: 'RakenOS 13 redesigns discovery in Raken Store. An editorial Today view, curated collections and a shared family library help you find apps worth installing.',
    notes: [
      'Raken Store|The new Today view highlights one featured app per day with an in-depth story from the Raken editorial team.',
      'Raken Store|Curated collections group apps by theme, such as "Focus at Work" or "Travel Light".',
      'Raken Store|Family Library lets up to six people share purchased RAS apps.',
      'Raken Store|App pages show a compatibility summary listing the capabilities an app needs and whether this device provides them.',
      'Raken Store|Search suggestions now include categories and developers, not only app names.',
      'Privacy|Store recommendations are calculated on the device from your Library, without uploading your usage history.',
      'RAS Runtime|RAS packages can include localized Store metadata for each supported language.',
    ],
    subjects: ['the Today view', 'curated collections', 'Family Library', 'the compatibility summary'],
    s1: 'RakenOS 13.0.1 fixes issues in the redesigned Raken Store.',
    f1: [
      'Raken Store|Fixed an issue where the Today story could open scrolled halfway down.',
      'Raken Store|Family Library now shows who in the family originally installed an app.',
    ],
    s2: 'RakenOS 13.0.2 polishes Store discovery and improves package security.',
    f2: [
      'Raken Store|Collections load their artwork progressively on slow connections.',
      'Raken Store|The compatibility summary explains why an app is unavailable instead of hiding it.',
    ],
  },
  {
    major: 14,
    title: 'Universal Search',
    summary: 'RakenOS 14 turns search into a system-wide tool. Search looks inside notes, files, settings and apps at once and understands simple filters.',
    notes: [
      'New|Universal Search finds apps, settings, notes, files and contacts from a single search field.',
      'New|Search filters such as `type:pdf`, `in:notes` and `modified:week` narrow down results as you type.',
      'Home Screen|Swipe down anywhere on the Home Screen to start searching.',
      'Files|Files content is indexed on the device, so search now matches text inside documents.',
      'Settings|Search results jump directly to the matching setting and briefly highlight it.',
      'Privacy|The search index is encrypted and stored only on the device. Clear it at any time from Privacy settings.',
      'RAS Runtime|RAS API level 14 introduces the search provider API so apps can contribute their own content to search.',
    ],
    subjects: ['Universal Search', 'search filters', 'the on-device search index', 'the search provider API'],
    s1: 'RakenOS 14.0.1 improves search accuracy and indexing reliability.',
    f1: [
      'Performance|The initial search index is built more slowly while the device is in use to avoid slowdowns.',
      'Files|Fixed an issue where renamed files were shown twice in search results.',
    ],
    s2: 'RakenOS 14.0.2 polishes Universal Search and includes security fixes.',
    f2: [
      'Settings|Recent searches can be removed individually with a swipe.',
      'Privacy|Search suggestions from RAS apps are hidden on the Lock Screen.',
    ],
  },
  {
    major: 15,
    title: 'Camera Pro',
    summary: 'RakenOS 15 unlocks the full potential of advanced camera hardware. Pro mode, RAW capture and a new Night mode arrive, and each feature is enabled automatically when the camera supports it.',
    notes: [
      'Camera|Pro mode offers manual shutter speed, ISO, white balance and focus on devices with advanced camera hardware.',
      'Camera|RAW capture saves an uncompressed image alongside the processed photo when the sensor supports it.',
      'Camera|Night mode combines multiple frames in low light. A progress ring shows how long to hold the device still.',
      'Camera|Focus peaking highlights the in-focus parts of the image while focusing manually.',
      'Gallery|RAW photos show a RAW badge and can be edited with extended exposure and highlight recovery ranges.',
      'System|Camera features are enabled from detected hardware capabilities instead of a fixed feature list.',
      'Developer APIs|RAS apps can query the camera capability level: basic, standard or advanced.',
    ],
    subjects: ['Pro mode', 'RAW capture', 'Night mode', 'focus peaking'],
    s1: 'RakenOS 15.0.1 improves photo quality and fixes issues in Pro mode.',
    f1: [
      'Camera|Improved noise reduction in Night mode photos of scenes with bright street lights.',
      'Camera|Manual focus settings are now preserved when switching between Photo and Pro mode.',
    ],
    s2: 'RakenOS 15.0.2 polishes Camera Pro and includes security improvements.',
    f2: [
      'Gallery|RAW files now display their full dimensions in the photo information panel.',
      'Camera|The histogram in Pro mode updates at a steadier rate.',
    ],
  },
  {
    major: 16,
    title: 'App Lifecycle',
    summary: 'RakenOS 16 changes how apps live in the background. A new task scheduler, app hibernation and state restoration make multitasking both more efficient and more predictable.',
    notes: [
      'System|App hibernation suspends apps you have not used for a while and releases their memory without losing their state.',
      'System|State restoration reopens an app exactly where you left it, even if the system closed it in the background.',
      'System|The new background task scheduler runs deferred work when the device is idle, charging or on Wi-Fi.',
      'Home Screen|Recent Apps shows a small indicator on apps that are hibernating.',
      'Battery|Hibernated apps consume no CPU time, which reduces standby drain.',
      'RAS Runtime|RAS API level 16 introduces the lifecycle states created, active, background, hibernated and restored.',
      'RScript|RScript 1.9 adds `on lifecycle` handlers so apps can save and restore their state.',
      'Developer APIs|Background tasks can declare required conditions such as `charging` or `unmetered`.',
    ],
    subjects: ['app hibernation', 'state restoration', 'the background task scheduler', 'lifecycle handlers'],
    s1: 'RakenOS 16.0.1 resolves issues with app hibernation and state restoration.',
    f1: [
      'System|Fixed an issue where an app restored from hibernation could show its splash screen twice.',
      'System|Media apps are no longer hibernated while a playback notification is visible.',
    ],
    s2: 'RakenOS 16.0.2 refines the app lifecycle and includes security fixes.',
    f2: [
      'Developer APIs|The lifecycle inspector in Developer options now shows the reason for each state change.',
      'Battery|Deferred tasks that repeatedly fail are backed off exponentially.',
    ],
  },
  {
    major: 17,
    title: 'Scanner Services',
    summary: 'RakenOS 17 introduces system scanner services. On devices with a dedicated 2D scanner, scanning becomes a first-class system feature with profiles, keyboard input and a Scanner app.',
    notes: [
      'New|On devices with a 2D scanner, the new Scanner app captures QR, Data Matrix, PDF417, Code 128 and EAN codes.',
      'New|Scan-to-field enters the scanned value into the focused text field in any app, like typing.',
      'Settings|Scanner settings appear automatically when a scanner is detected, with symbologies, feedback and trigger options.',
      'Settings|Scanner profiles apply different prefixes, suffixes and symbologies per app.',
      'Control Center|A Scanner tile is available on devices with scanner hardware.',
      'RAS Runtime|RAS API level 17 adds a scanner API that is only exposed when the capability is present.',
      'Developer APIs|Apps receive structured scan results with symbology, raw bytes and decoded text.',
    ],
    subjects: ['the Scanner app', 'scan-to-field', 'scanner profiles', 'the scanner API'],
    s1: 'RakenOS 17.0.1 improves scanning reliability.',
    f1: [
      'Settings|Fixed an issue where a scanner profile suffix was not applied to Data Matrix codes.',
      'System|Improved decoding of damaged or low-contrast codes.',
    ],
    s2: 'RakenOS 17.0.2 polishes scanner services and includes security fixes.',
    f2: [
      'Accessibility|Successful scans are announced by Raken Narrator.',
      'Privacy|Scan history is kept for 24 hours by default and can be switched off.',
    ],
  },
  {
    major: 18,
    title: 'Focus',
    summary: 'RakenOS 18 introduces Focus profiles that shape the whole device around what you are doing, from which notifications arrive to which Home Screen page is visible.',
    notes: [
      'New|Focus profiles such as Work, Personal and Sleep filter notifications and calls based on people and apps you choose.',
      'New|Each Focus can show its own Home Screen page, hiding apps that are not relevant.',
      'Lock Screen|The Lock Screen shows the active Focus and the time it ends.',
      'Notifications|Notifications silenced by a Focus are summarised when the Focus ends.',
      'Control Center|The Focus tile switches profiles and shows suggested profiles based on time and location.',
      'Settings|Focus schedules can start automatically at a time, when you connect to a network or when you open an app.',
      'RAS Runtime|RAS API level 18 lets apps read the current Focus category and filter their own content.',
    ],
    subjects: ['Focus profiles', 'Focus Home Screen pages', 'Focus schedules', 'the Focus summary'],
    s1: 'RakenOS 18.0.1 improves Focus reliability and scheduling.',
    f1: [
      'Settings|Fixed an issue where a Focus schedule could fail to start after changing time zones.',
      'Home Screen|Hidden Home Screen pages no longer reappear briefly when a Focus ends.',
    ],
    s2: 'RakenOS 18.0.2 polishes Focus and includes security improvements.',
    f2: [
      'Notifications|The Focus summary groups notifications by person instead of by app.',
      'Lock Screen|The Focus indicator is easier to read over bright wallpapers.',
    ],
  },
  {
    major: 19,
    title: 'Files Pro',
    summary: 'RakenOS 19 makes Files a professional tool with external storage, compressed archives and version history for your documents.',
    notes: [
      'Files|USB storage devices appear in Files as soon as they are connected, with safe eject.',
      'Files|Create and extract ZIP archives directly in Files, with progress for large archives.',
      'Files|Version history keeps earlier versions of documents for 30 days so you can restore previous content.',
      'Files|Column view on larger displays shows folder hierarchy side by side.',
      'Files|Batch rename with numbering, find-and-replace and date patterns.',
      'Notes|Notes are now stored as documents and benefit from version history.',
      'RAS Runtime|RAS API level 19 adds file coordination so two apps can safely edit the same document.',
    ],
    subjects: ['external storage support', 'ZIP archives', 'document version history', 'batch rename'],
    s1: 'RakenOS 19.0.1 fixes issues in Files.',
    f1: [
      'Files|Fixed an issue where extracting a ZIP archive with very long file names could fail silently.',
      'Files|Safe eject now waits for pending writes before reporting that storage can be removed.',
    ],
    s2: 'RakenOS 19.0.2 polishes Files and includes security improvements.',
    f2: [
      'Security|Archives containing paths that point outside the destination folder are now rejected.',
      'Files|Version history shows the app that created each version.',
    ],
  },
];
