'use strict';
// Authored release content for RakenOS generations 20–39.

module.exports = [
  {
    major: 20,
    title: 'Raken Design 2',
    summary: 'RakenOS 20 introduces Raken Design 2, the first complete redesign of the system interface. A new type scale, accent colours derived from your wallpaper and a rebuilt Settings app give RakenOS a calmer, more consistent look.',
    notes: [
      'New|Raken Design 2 introduces a new type scale, refined spacing and updated system icons across every built-in app.',
      'New|Accent colours can be derived from the wallpaper. RakenOS picks a colour with guaranteed contrast in light and dark mode.',
      'Settings|Settings has been rebuilt with a search-first layout, grouped rows and a clearer hierarchy.',
      'Home Screen|App icons use a new shape with optical size correction for small and large grid layouts.',
      'Control Center|Control Center tiles are redesigned with state labels, so you can see at a glance what each tile controls.',
      'Accessibility|Increase Contrast darkens secondary text and adds borders to controls throughout Raken Design 2.',
      'Developer APIs|RDesign 2 components adopt the new design tokens automatically, without app updates.',
      'RAS Runtime|RAS API level 20 exposes design tokens for colour, typography, spacing and motion.',
    ],
    subjects: ['Raken Design 2', 'wallpaper accent colours', 'the rebuilt Settings app', 'the redesigned Control Center tiles'],
    s1: 'RakenOS 20.0.1 fixes visual issues found after the Raken Design 2 rollout.',
    f1: [
      'Settings|Fixed an issue where some rows in Settings used the previous generation of icons.',
      'Home Screen|Wallpaper accent colours are recalculated when the wallpaper is changed from Gallery.',
    ],
    s2: 'RakenOS 20.0.2 polishes Raken Design 2 and includes security fixes.',
    f2: [
      'Accessibility|Increase Contrast now also applies to widgets on the Home Screen.',
      'Control Center|Tile labels truncate gracefully in languages with long words.',
    ],
  },
  {
    major: 21,
    title: 'Intelligent Resource Management',
    summary: 'RakenOS 21 introduces intelligent resource management. The system predicts memory pressure, schedules work around thermal conditions and gives foreground apps priority where it matters.',
    notes: [
      'System|Memory pressure prediction frees memory before it is needed, instead of closing apps when memory is already exhausted.',
      'System|Thermal-aware scheduling spreads intensive background work over time when the device is warm.',
      'Performance|The foreground app receives priority access to CPU and storage while you interact with it.',
      'Performance|Storage writes from background apps are coalesced to reduce latency for the app in use.',
      'Battery|Thermal management lowers peak power when charging in a warm environment.',
      'Settings|A new Resource Monitor in Battery settings shows memory and thermal state history.',
      'Developer APIs|Apps can register for memory pressure hints and release caches early.',
    ],
    subjects: ['memory pressure prediction', 'thermal-aware scheduling', 'foreground priority', 'the Resource Monitor'],
    s1: 'RakenOS 21.0.1 fine-tunes intelligent resource management.',
    f1: [
      'System|Reduced the number of apps closed in the background when a large app is launched.',
      'Performance|Fixed a delay when returning to a game after a phone call.',
    ],
    s2: 'RakenOS 21.0.2 polishes resource management and includes security fixes.',
    f2: [
      'Settings|The Resource Monitor explains each thermal event in plain language.',
      'Battery|Background indexing is postponed while the device is above its normal temperature range.',
    ],
  },
  {
    major: 22,
    title: 'Continuity',
    summary: 'RakenOS 22 introduces cross-device services. Continue what you are doing on another RakenOS device, copy on one device and paste on another, and see all your devices in one place.',
    notes: [
      'New|Handoff lets you continue a note, a web page or a Store search on another RakenOS device signed in to the same Raken Account.',
      'New|Universal Clipboard: copy text or an image on one device and paste it on another nearby device.',
      'Settings|The Devices page lists every RakenOS device on your account by the name you gave it, with its last seen time.',
      'Connectivity|Cross-device services use end-to-end encrypted connections over Wi-Fi or Bluetooth.',
      'Notes|Notes opened through Handoff keep their cursor position and scroll offset.',
      'Privacy|Universal Clipboard contents expire after two minutes and are never stored in the cloud.',
      'RAS Runtime|RAS API level 22 introduces the continuity API for passing app state between devices.',
    ],
    subjects: ['Handoff', 'Universal Clipboard', 'the Devices page', 'the continuity API'],
    s1: 'RakenOS 22.0.1 improves reliability of cross-device services.',
    f1: [
      'Connectivity|Handoff suggestions appear more quickly after the other device is unlocked.',
      'Settings|Fixed an issue where a renamed device kept its previous name on the Devices page.',
    ],
    s2: 'RakenOS 22.0.2 polishes Continuity and includes security fixes.',
    f2: [
      'Security|Devices removed from your account are immediately excluded from Universal Clipboard.',
      'Browser|Handoff for web pages now preserves the reader mode setting.',
    ],
  },
  {
    major: 23,
    title: 'Notification System 2',
    summary: 'RakenOS 23 replaces the notification engine. Notification summaries, Live Status updates and notification channels for RAS apps make notifications quieter and more informative.',
    notes: [
      'Notifications|The new notification engine delivers notifications as scheduled summaries, such as 08:00 and 18:00, for apps you choose.',
      'Notifications|Live Status shows ongoing activities such as timers, deliveries and downloads as a single updating notification.',
      'Notifications|Notification channels let you control categories within an app, for example keeping messages on and promotions off.',
      'Lock Screen|Live Status items appear at the top of the Lock Screen and update in real time.',
      'Notification Center|Notification Center has a new layout with Today and Earlier sections.',
      'RAS Runtime|RAS API level 23 introduces notification channels and the Live Status API.',
      'Developer APIs|Notifications can now include progress, a countdown or a two-line status.',
    ],
    subjects: ['notification summaries', 'Live Status', 'notification channels', 'the new notification engine'],
    s1: 'RakenOS 23.0.1 fixes issues with the new notification engine.',
    f1: [
      'Notifications|Fixed an issue where a notification summary could be delivered twice after a restart.',
      'Lock Screen|Live Status timers no longer drift after the device has been in deep sleep.',
    ],
    s2: 'RakenOS 23.0.2 polishes notifications and includes security fixes.',
    f2: [
      'Notifications|Summaries now include a short count of what was held back in each app.',
      'Accessibility|Live Status updates are announced at most once every 30 seconds by Raken Narrator.',
    ],
  },
  {
    major: 24,
    title: 'RAS APIs 2',
    summary: 'RakenOS 24 greatly expands what RAS apps can do. Background fetch, secure storage, app intents and share targets give developers the tools to build complete applications.',
    notes: [
      'RAS Runtime|RAS API level 24 introduces background fetch with system-managed scheduling.',
      'RAS Runtime|Secure storage keeps small secrets such as tokens in hardware-backed storage where available.',
      'RAS Runtime|App intents expose actions such as "Start workout" to Search, widgets and routines.',
      'RScript|RScript 2.3 adds `async` functions, `await` and structured error handling with `try` and `catch`.',
      'Developer APIs|The RAS packager now reports unused permissions and missing accessibility labels.',
      'Raken Store|App pages list the app intents an app provides.',
      'Security|Secure storage entries are deleted automatically when an app is removed.',
    ],
    subjects: ['background fetch', 'secure storage', 'app intents', 'RScript async functions'],
    s1: 'RakenOS 24.0.1 improves the new RAS APIs.',
    f1: [
      'RAS Runtime|Fixed an issue where background fetch did not run after an app update until the next restart.',
      'RScript|Error messages from rejected `await` calls now include the original line number.',
    ],
    s2: 'RakenOS 24.0.2 polishes RAS APIs and includes security fixes.',
    f2: [
      'Developer APIs|The RAS packager now validates intent parameter types.',
      'Security|Secure storage now requires the device to have been unlocked once since restart.',
    ],
  },
  {
    major: 25,
    title: 'Security Architecture',
    summary: 'RakenOS 25 introduces a new security architecture. System components are verified at every start, the app sandbox is rebuilt, and RAS signatures support key rotation.',
    notes: [
      'Security|Verified start checks the integrity of every RakenOS system component before it is loaded.',
      'Security|The second-generation sandbox isolates each RAS app in its own process with a minimal set of system services.',
      'Security|RAS signature format 2 supports developer key rotation without breaking updates.',
      'Security|Security status now shows the date of the latest security content and whether verified start succeeded.',
      'Privacy|Apps can no longer read the list of other installed apps without a declared reason.',
      'RAS Runtime|RAS API level 25 introduces sandbox profiles and denies undeclared system services by default.',
      'Developer APIs|The RAS signing tool can rotate keys and publish a signed rotation record.',
    ],
    subjects: ['verified start', 'the second-generation sandbox', 'RAS signature format 2', 'key rotation'],
    s1: 'RakenOS 25.0.1 refines the new security architecture.',
    f1: [
      'Security|Fixed an issue where verified start could report a warning after interrupted storage maintenance.',
      'RAS Runtime|Improved compatibility of older RAS apps with the new sandbox.',
    ],
    s2: 'RakenOS 25.0.2 strengthens security further.',
    f2: [
      'Security|Key rotation records are now checked against the Store transparency log.',
      'Settings|Security status links directly to the setting that needs your attention.',
    ],
  },
  {
    major: 26,
    title: 'Keyboard and Input',
    summary: 'RakenOS 26 introduces a completely new keyboard with on-device dictation, better predictions and a floating layout for one-handed typing.',
    notes: [
      'New|A new system keyboard with improved autocorrection that learns on the device.',
      'New|On-device dictation works without an internet connection and inserts punctuation automatically.',
      'New|Floating keyboard: pinch the keyboard to make it smaller and move it anywhere on the screen.',
      'Accessibility|Key repeat and slow keys options for users who need more time when typing.',
      'Settings|Text replacement shortcuts can be created and synced across your RakenOS devices.',
      'Privacy|Keyboard learning data is stored on the device and can be reset from Privacy settings.',
      'Developer APIs|Text fields in RDesign can request specialised layouts such as numeric, email and URL.',
    ],
    subjects: ['the new system keyboard', 'on-device dictation', 'the floating keyboard', 'text replacement'],
    s1: 'RakenOS 26.0.1 improves typing accuracy and dictation.',
    f1: [
      'System|Fixed an issue where autocorrection changed words in URLs and email addresses.',
      'System|Dictation handles pauses between sentences more naturally.',
    ],
    s2: 'RakenOS 26.0.2 polishes the keyboard and includes security fixes.',
    f2: [
      'Accessibility|Key popups are larger when Increase Contrast is enabled.',
      'Privacy|The keyboard never learns from text typed in password fields or private browsing tabs.',
    ],
  },
  {
    major: 27,
    title: 'Personal Lock Screen',
    summary: 'RakenOS 27 makes the Lock Screen personal. Choose the clock style, add widgets and create several Lock Screens that switch automatically with your Focus.',
    notes: [
      'Lock Screen|Customise the clock font, weight and colour directly on the Lock Screen by pressing and holding.',
      'Lock Screen|Lock Screen widgets show battery, next alarm, weather from RAS apps and more below the clock.',
      'Lock Screen|Create multiple Lock Screens and link each one to a Focus profile.',
      'Lock Screen|A depth effect places the clock behind the subject of portrait wallpapers.',
      'Notifications|Notifications can appear as a compact stack at the bottom of the Lock Screen.',
      'RAS Runtime|RAS API level 27 adds a Lock Screen widget family with privacy-aware redaction.',
    ],
    subjects: ['the Lock Screen editor', 'Lock Screen widgets', 'linked Lock Screens', 'the depth effect'],
    s1: 'RakenOS 27.0.1 fixes issues with Lock Screen customisation.',
    f1: [
      'Lock Screen|Fixed an issue where a custom clock colour was reset after changing wallpaper.',
      'Lock Screen|The depth effect is now disabled automatically if it would cover the time.',
    ],
    s2: 'RakenOS 27.0.2 polishes the Lock Screen and includes security fixes.',
    f2: [
      'Privacy|Lock Screen widgets redact personal content until Face or PIN authentication has occurred once.',
      'Lock Screen|The notification stack expands with a smoother animation.',
    ],
  },
  {
    major: 28,
    title: 'Browser 2',
    summary: 'RakenOS 28 introduces a redesigned Browser with tab groups, Reader mode, tracker blocking and private browsing that locks when you leave it.',
    notes: [
      'Browser|Tab groups organise related tabs and sync their order across your RakenOS devices.',
      'Browser|Reader mode removes clutter from articles and lets you adjust font, size and background.',
      'Browser|Tracker blocking prevents known cross-site trackers from loading, with a per-site report.',
      'Browser|Private browsing tabs are locked when you leave the Browser and require your PIN to reopen.',
      'Browser|The address bar moves to the bottom of the screen for easier one-handed use.',
      'Privacy|Browser history can be automatically removed after one day, one week or one month.',
      'Developer APIs|RAS apps can open web content in a Browser sheet that shares cookies with the Browser.',
    ],
    subjects: ['tab groups', 'Reader mode', 'tracker blocking', 'locked private browsing'],
    s1: 'RakenOS 28.0.1 improves the redesigned Browser.',
    f1: [
      'Browser|Fixed an issue where Reader mode was unavailable for some articles split across multiple pages.',
      'Browser|Tab groups created on another device now appear without needing a restart.',
    ],
    s2: 'RakenOS 28.0.2 polishes the Browser and includes security fixes.',
    f2: [
      'Security|Improved isolation between private and standard browsing tabs.',
      'Browser|The tracker report shows the number of trackers blocked in the last 30 days.',
    ],
  },
  {
    major: 29,
    title: 'Sync Everywhere',
    summary: 'RakenOS 29 expands cross-device services with synced notes and files, and makes moving to a new RakenOS device a matter of minutes.',
    notes: [
      'New|Notes and selected Files folders sync across your RakenOS devices with end-to-end encryption.',
      'New|Device-to-device setup transfers apps, settings and your Library from another RakenOS device during setup.',
      'Raken Store|Your Store Library is restored automatically on a new device, including app order on the Home Screen.',
      'Files|Synced folders show sync status per file and resolve conflicts by keeping both versions.',
      'Settings|The Devices page shows which content each device syncs.',
      'Connectivity|Sync pauses automatically on metered connections unless you allow it.',
      'RAS Runtime|RAS API level 29 introduces app data sync with per-app encryption keys.',
    ],
    subjects: ['Notes sync', 'Files folder sync', 'device-to-device setup', 'app data sync'],
    s1: 'RakenOS 29.0.1 improves sync reliability.',
    f1: [
      'Files|Fixed an issue where a large file could restart syncing from the beginning after a brief disconnection.',
      'Notes|Checklist changes made offline are merged correctly when the device reconnects.',
    ],
    s2: 'RakenOS 29.0.2 polishes sync and includes security fixes.',
    f2: [
      'Settings|Sync status now shows the time of the last successful sync for each device.',
      'Security|Removing a device from your account revokes its sync keys immediately.',
    ],
  },
  {
    major: 30,
    title: 'Productivity',
    summary: 'RakenOS 30 is focused on getting things done. Notes gains checklists and tables, Quick Actions put common tasks one press away and clipboard history remembers what you copied.',
    notes: [
      'Notes|Checklists with drag-to-reorder and automatic sorting of completed items.',
      'Notes|Tables with up to 12 columns, resizable cells and swipe to add rows.',
      'New|Quick Actions: press and hold an app icon to jump directly to common tasks such as "New Note" or "Start Timer".',
      'New|Clipboard history keeps the last 20 items you copied. Pin items to keep them permanently.',
      'Home Screen|Press and hold an empty area of the Home Screen to create a new note from anywhere.',
      'Privacy|Clipboard history never includes content copied from password fields and is cleared after 24 hours by default.',
      'RAS Runtime|RAS API level 30 lets apps declare Quick Actions in their manifest.',
    ],
    subjects: ['Notes checklists', 'Notes tables', 'Quick Actions', 'clipboard history'],
    s1: 'RakenOS 30.0.1 improves the new productivity features.',
    f1: [
      'Notes|Fixed an issue where a table could lose its last column when pasted into another note.',
      'Home Screen|Quick Actions open faster from the dock.',
    ],
    s2: 'RakenOS 30.0.2 polishes productivity features and includes security fixes.',
    f2: [
      'Privacy|Clipboard history can be switched off completely.',
      'Notes|Completed checklist items can be hidden with a single tap.',
    ],
  },
  {
    major: 31,
    title: 'Multitasking 2',
    summary: 'RakenOS 31 builds on Split View with floating windows and drag and drop between apps.',
    notes: [
      'New|Floating windows let an app hover above another app. Tuck a window to the edge to keep it within reach.',
      'New|Drag and drop text, images and files between apps in Split View or floating windows.',
      'Home Screen|Recent Apps remembers window arrangements, including floating windows.',
      'Files|Drag several files at once from Files into another app.',
      'Accessibility|Floating windows can be moved with Switch Control and hardware keyboards.',
      'RAS Runtime|RAS API level 31 introduces drag sources, drop targets and a resizable window API.',
    ],
    subjects: ['floating windows', 'drag and drop', 'window arrangements', 'the drop target API'],
    s1: 'RakenOS 31.0.1 improves stability of floating windows and drag and drop.',
    f1: [
      'System|Fixed an issue where a floating window could be restored off-screen after rotation.',
      'Files|Dropping a folder into another app now copies its contents in the right order.',
    ],
    s2: 'RakenOS 31.0.2 polishes multitasking and includes security fixes.',
    f2: [
      'Security|Dropped content is only readable by the receiving app until the drop completes.',
      'Home Screen|Tucked floating windows show a small edge handle with the app colour.',
    ],
  },
  {
    major: 32,
    title: 'Privacy Report',
    summary: 'RakenOS 32 delivers some of the biggest privacy improvements in RakenOS history: an App Privacy Report, approximate location and alerts when apps read your clipboard.',
    notes: [
      'Privacy|The App Privacy Report lists every sensitive data access and network domain contacted by each app over 7 days.',
      'Privacy|Approximate location shares an area of a few kilometres instead of your exact position.',
      'Privacy|A banner appears when an app reads content from the clipboard that was copied in another app.',
      'Privacy|Photo access can be limited to selected photos, and the selection can be changed at any time.',
      'Privacy|Local network access now requires permission, preventing apps from scanning devices on your network.',
      'Settings|Privacy settings have a new overview with suggestions for tightening access.',
      'RAS Runtime|RAS API level 32 requires apps to declare the purpose of every sensitive permission.',
    ],
    subjects: ['the App Privacy Report', 'approximate location', 'clipboard access alerts', 'limited photo access'],
    s1: 'RakenOS 32.0.1 refines the new privacy features.',
    f1: [
      'Privacy|Fixed an issue where the App Privacy Report listed the same domain several times with different capitalisation.',
      'Privacy|Clipboard alerts no longer appear when you paste into the same app you copied from.',
    ],
    s2: 'RakenOS 32.0.2 strengthens privacy protections and includes security fixes.',
    f2: [
      'Privacy|Apps granted limited photo access can no longer read metadata of unselected photos.',
      'Settings|Privacy suggestions can be dismissed individually.',
    ],
  },
  {
    major: 33,
    title: 'Backup and Recovery',
    summary: 'RakenOS 33 introduces encrypted backups and a redesigned recovery experience, so your data is safe even when something goes wrong.',
    notes: [
      'New|Encrypted backups save apps, settings, notes, files and Home Screen layout, protected by your PIN.',
      'New|Restore from backup is available during setup and shows exactly what will be restored.',
      'System|The redesigned recovery environment offers Restart, Safe start, Restore backup and Reset.',
      'System|RakenOS keeps the previous system components so a failed update can be rolled back automatically.',
      'Settings|Backup settings show the size, date and contents of every backup.',
      'Security|Backups are encrypted on the device before they leave it.',
      'RAS Runtime|RAS API level 33 lets apps exclude caches and large regenerable data from backups.',
    ],
    subjects: ['encrypted backups', 'restore during setup', 'the recovery environment', 'automatic rollback'],
    s1: 'RakenOS 33.0.1 improves backup reliability.',
    f1: [
      'System|Fixed an issue where a backup could stop at 99% when a large file changed during the backup.',
      'Settings|Backup progress now continues correctly when the display turns off.',
    ],
    s2: 'RakenOS 33.0.2 polishes backup and recovery and includes security fixes.',
    f2: [
      'System|Safe start now shows which component was disabled and why.',
      'Security|Old backup encryption keys are destroyed when you change your PIN.',
    ],
  },
  {
    major: 34,
    title: 'Routines',
    summary: 'RakenOS 34 introduces Raken Routines, an automation system that runs actions when something happens, built on RScript and app intents.',
    notes: [
      'New|Raken Routines run actions automatically at a time, at a location, when a Focus starts or when you connect an accessory.',
      'New|Build routines visually from actions such as "Set brightness", "Start Focus", "Create note" and app intents.',
      'New|Advanced users can write routines directly in RScript.',
      'Settings|Routines can require confirmation before they run, shown as a notification.',
      'Privacy|Routines that use location run entirely on the device.',
      'RScript|RScript 3.4 adds a `routine` block, triggers and a standard library for system actions.',
      'RAS Runtime|RAS API level 34 lets app intents be used as routine actions with typed parameters.',
    ],
    subjects: ['Raken Routines', 'the visual routine builder', 'RScript routines', 'routine triggers'],
    s1: 'RakenOS 34.0.1 improves Routines.',
    f1: [
      'Settings|Fixed an issue where a routine triggered by an accessory connection ran twice.',
      'RScript|Routine scripts now report runtime errors in the routine history.',
    ],
    s2: 'RakenOS 34.0.2 polishes Routines and includes security fixes.',
    f2: [
      'Security|Routines created by RAS apps require your approval before their first run.',
      'Settings|Routine history keeps the last 100 runs with their outcome.',
    ],
  },
  {
    major: 35,
    title: 'Shared Files',
    summary: 'RakenOS 35 makes collaboration part of Files with shared folders, activity and conflict resolution.',
    notes: [
      'Files|Share a folder with other people and choose whether they can view or edit.',
      'Files|The Activity panel shows who added, changed or removed files in a shared folder.',
      'Files|Conflicting edits are detected and presented side by side, so you can choose which version to keep.',
      'Files|Shared folders show an avatar of the person who last changed each file.',
      'Notes|Notes can be shared for collaboration with live cursors for each participant.',
      'Notifications|Notifications summarise changes in shared folders instead of one notification per file.',
    ],
    subjects: ['shared folders', 'the Activity panel', 'conflict resolution', 'collaborative notes'],
    s1: 'RakenOS 35.0.1 improves collaboration reliability.',
    f1: [
      'Files|Fixed an issue where a participant could see an outdated file list after being re-invited.',
      'Notes|Live cursors disappear promptly when a participant leaves the note.',
    ],
    s2: 'RakenOS 35.0.2 polishes shared files and includes security fixes.',
    f2: [
      'Security|Links to shared folders can now expire after a chosen number of days.',
      'Files|Activity can be filtered by person.',
    ],
  },
  {
    major: 36,
    title: 'Private Space',
    summary: 'RakenOS 36 introduces Private Space, a separate protected area for apps and files, along with hidden apps and a secure folder with its own PIN.',
    notes: [
      'Privacy|Private Space is a separate area with its own apps, files and notifications, protected by a separate PIN.',
      'Privacy|When Private Space is locked, its apps are fully stopped and do not appear in Search, Recent Apps or Settings.',
      'Privacy|Hide any app from the Home Screen and Search. Hidden apps are listed in a protected section of the App Library.',
      'Files|Secure Folder encrypts its contents with a key that is only available while it is unlocked.',
      'Security|Private Space uses a separate encryption key that is removed from memory when it locks.',
      'RAS Runtime|Apps installed in Private Space have their own storage, permissions and secure storage entries.',
    ],
    subjects: ['Private Space', 'hidden apps', 'Secure Folder', 'separate Private Space keys'],
    s1: 'RakenOS 36.0.1 improves Private Space.',
    f1: [
      'Privacy|Fixed an issue where a notification from Private Space could briefly appear after it was locked.',
      'Files|Moving large files into Secure Folder is faster.',
    ],
    s2: 'RakenOS 36.0.2 polishes Private Space and includes security fixes.',
    f2: [
      'Security|Private Space locks automatically after a chosen period of inactivity.',
      'Privacy|Screenshots are blocked inside Private Space unless you allow them.',
    ],
  },
  {
    major: 37,
    title: 'Seamless Updates',
    summary: 'RakenOS 37 changes how system updates are installed. Updates now install in the background to an inactive system slot and take effect after a quick restart, with rollback protection and a new Safe mode.',
    notes: [
      'System|Seamless updates install system components into an inactive slot while you keep using the device.',
      'System|If the updated system fails to start, RakenOS switches back to the previous slot automatically.',
      'Security|Rollback protection prevents installing older system components that contain fixed security issues.',
      'System|Safe mode starts RakenOS with only built-in apps, making it easy to identify a problematic RAS app.',
      'Settings|System Update shows each phase: downloading, verifying, preparing and ready to restart.',
      'Settings|Choose a time window for automatic installation, for example between 02:00 and 05:00.',
      'Battery|Updates are installed only when the battery is above 30% or the device is charging.',
    ],
    subjects: ['seamless updates', 'automatic slot fallback', 'rollback protection', 'Safe mode'],
    s1: 'RakenOS 37.0.1 improves the new update system.',
    f1: [
      'System|Fixed an issue where the preparing phase could take longer when storage was nearly full.',
      'Settings|The installation window now follows the local time after travelling.',
    ],
    s2: 'RakenOS 37.0.2 polishes seamless updates and includes security fixes.',
    f2: [
      'Security|Rollback protection now also covers the RAS runtime and RScript engine.',
      'System|Safe mode shows a persistent banner with a Restart normally button.',
    ],
  },
  {
    major: 38,
    title: 'Clock and Time',
    summary: 'RakenOS 38 refreshes Clock with Bedtime, smarter alarms and world clock widgets, and brings consistent time handling across the system.',
    notes: [
      'Clock|Bedtime reminds you to wind down and silences notifications until your wake-up alarm.',
      'Clock|Alarms can skip public holidays and the next occurrence without being turned off.',
      'Clock|Gradual wake-up slowly increases alarm volume over 30 seconds.',
      'Home Screen|New World Clock widgets show up to four cities with day and night indication.',
      'Clock|Multiple timers can run at the same time, each with its own label.',
      'Lock Screen|Running timers appear as Live Status items.',
      'System|Time zone changes while travelling are detected faster and shown in a notification.',
    ],
    subjects: ['Bedtime', 'alarm skipping', 'World Clock widgets', 'multiple timers'],
    s1: 'RakenOS 38.0.1 improves Clock reliability.',
    f1: [
      'Clock|Fixed an issue where a skipped alarm could also skip the following day.',
      'Clock|Timers keep running correctly after a system update restart.',
    ],
    s2: 'RakenOS 38.0.2 polishes Clock and includes security fixes.',
    f2: [
      'Accessibility|Alarms can flash the screen as an alternative to sound.',
      'Clock|Stopwatch laps can be copied as text.',
    ],
  },
  {
    major: 39,
    title: 'Desktop Mode',
    summary: 'RakenOS 39 brings desktop-class productivity. Connect an external display for Desktop mode with resizable windows, window snapping and keyboard shortcuts.',
    notes: [
      'New|Desktop mode starts when an external display is connected, with a taskbar and resizable app windows.',
      'New|Window snapping arranges windows in halves, thirds or quarters by dragging them to the edge.',
      'New|System-wide keyboard shortcuts for switching apps, taking screenshots and opening Search.',
      'Files|Files shows a toolbar and sidebar in Desktop mode.',
      'Browser|Desktop mode requests desktop versions of websites by default.',
      'Accessibility|Pointer size and colour can be adjusted for Desktop mode.',
      'RAS Runtime|RAS API level 39 adds pointer events, hover states and window size classes for large displays.',
    ],
    subjects: ['Desktop mode', 'window snapping', 'system keyboard shortcuts', 'pointer support'],
    s1: 'RakenOS 39.0.1 improves Desktop mode.',
    f1: [
      'System|Fixed an issue where windows lost their size after the external display went to sleep.',
      'Accessibility|Keyboard focus is now visible on the taskbar.',
    ],
    s2: 'RakenOS 39.0.2 polishes Desktop mode and includes security fixes.',
    f2: [
      'System|Window arrangements are remembered separately for each external display.',
      'Performance|Reduced input latency for pointer devices.',
    ],
  },
];
