'use strict';
// Authored release content for RakenOS generations 40–59.

module.exports = [
  {
    major: 40,
    title: 'RAS Runtime 4',
    summary: 'RakenOS 40 introduces a modernised runtime. RAS Runtime 4 compiles RScript ahead of time, runs every app in an isolated worker and reduces memory use across the board.',
    notes: [
      'RAS Runtime|RAS Runtime 4 compiles RScript to compact bytecode during installation, so apps start without parsing source code.',
      'RAS Runtime|Each app runs in an isolated worker with its own heap, so a misbehaving app cannot slow down the interface.',
      'RScript|RScript 4.0 introduces modules with `import` and `export`, and a standard library split into packages.',
      'Performance|Typical RAS apps use 30% less memory and launch 45% faster than on RakenOS 39.',
      'Developer APIs|The runtime inspector shows bytecode size, worker memory and message latency for each app.',
      'Raken Store|Apps are compiled for the device after download. Store shows "Optimising" while this happens.',
      'Security|The bytecode verifier rejects malformed programs before they are executed.',
    ],
    subjects: ['RAS Runtime 4', 'ahead-of-time RScript compilation', 'isolated app workers', 'RScript modules'],
    s1: 'RakenOS 40.0.1 refines RAS Runtime 4.',
    f1: [
      'RAS Runtime|Fixed an issue where some apps compiled on RakenOS 39 were optimised again after every restart.',
      'RScript|Improved compatibility with RScript 3 code that used reserved words as map keys.',
    ],
    s2: 'RakenOS 40.0.2 polishes the new runtime and includes security fixes.',
    f2: [
      'Performance|Bytecode compilation now uses efficiency cores when available.',
      'Security|The bytecode verifier checks jump targets across module boundaries.',
    ],
  },
  {
    major: 41,
    title: 'Motion Engine',
    summary: 'RakenOS 41 introduces a new animation engine. Every transition is physics-based and interruptible, so the interface follows your finger naturally and never makes you wait.',
    notes: [
      'New|The new motion engine uses spring physics for every system transition, from opening apps to expanding notifications.',
      'New|All gestures are interruptible. Catch an app while it closes and pull it back open.',
      'Home Screen|Opening and closing apps animates from and to the exact icon position, including icons in folders.',
      'Control Center|Control Center follows your finger continuously instead of snapping open.',
      'Performance|Animations render at the full refresh rate of high-refresh displays.',
      'Accessibility|Reduce Motion now uses dedicated gentle transitions instead of removing motion entirely.',
      'Developer APIs|RDesign supports spring transitions with damping and response parameters.',
    ],
    subjects: ['the motion engine', 'interruptible gestures', 'spring transitions', 'icon-anchored app animations'],
    s1: 'RakenOS 41.0.1 refines the new motion engine.',
    f1: [
      'Home Screen|Fixed an issue where an app could animate to the wrong icon after the Home Screen was rearranged.',
      'Performance|Reduced frame drops when opening Control Center during heavy background work.',
    ],
    s2: 'RakenOS 41.0.2 polishes motion and includes security fixes.',
    f2: [
      'Battery|Animations lower their frame rate when Battery Saver is enabled.',
      'Accessibility|Spring transitions respect the animation speed setting in Accessibility.',
    ],
  },
  {
    major: 42,
    title: 'Raken Store, Third Generation',
    summary: 'RakenOS 42 introduces the third generation of Raken Store with a new design, subscription management and verified developer badges.',
    notes: [
      'Raken Store|The redesigned Raken Store has a new Discover tab with personalised rows and editorial stories.',
      'Raken Store|Manage all subscriptions from your Store account, with renewal dates and one-tap cancellation.',
      'Raken Store|Verified developer badges show that a developer identity has been confirmed by Raken.',
      'Raken Store|App pages include a Privacy summary based on the permissions and purposes declared in the RAS manifest.',
      'Raken Store|Pre-orders let you install an app automatically on its release day.',
      'Security|Store packages include a transparency proof that is verified before installation.',
    ],
    subjects: ['the third-generation Raken Store', 'subscription management', 'verified developer badges', 'Store privacy summaries'],
    s1: 'RakenOS 42.0.1 improves the new Raken Store.',
    f1: [
      'Raken Store|Fixed an issue where some subscriptions showed an incorrect renewal date.',
      'Raken Store|Discover rows no longer repeat the same app in consecutive rows.',
    ],
    s2: 'RakenOS 42.0.2 polishes Raken Store and includes security fixes.',
    f2: [
      'Raken Store|Privacy summaries now include data retention periods declared by developers.',
      'Accessibility|Store ratings are read as full sentences by Raken Narrator.',
    ],
  },
  {
    major: 43,
    title: 'Accessibility, Advanced',
    summary: 'RakenOS 43 introduces Switch Control, Live Captions and Voice Control, making every part of RakenOS usable without touching the screen.',
    notes: [
      'Accessibility|Switch Control lets you operate RakenOS with one or more external switches or with head movements via the front camera.',
      'Accessibility|Live Captions transcribe any audio playing on the device in real time, entirely on the device.',
      'Accessibility|Voice Control lets you tap, scroll and type by voice, with numbered overlays for every control.',
      'Accessibility|Sound Recognition notifies you about doorbells, alarms and crying babies.',
      'Settings|The Accessibility Shortcut can toggle any combination of features with a triple press.',
      'RAS Runtime|RAS API level 43 lets apps provide custom actions for Switch Control and Voice Control.',
    ],
    subjects: ['Switch Control', 'Live Captions', 'Voice Control', 'Sound Recognition'],
    s1: 'RakenOS 43.0.1 improves the new accessibility features.',
    f1: [
      'Accessibility|Live Captions keep up better with fast speech.',
      'Accessibility|Fixed an issue where Voice Control overlays were misaligned in Split View.',
    ],
    s2: 'RakenOS 43.0.2 polishes accessibility and includes security fixes.',
    f2: [
      'Accessibility|Live Captions can be moved and resized.',
      'Privacy|Sound Recognition models run fully on the device and never record audio.',
    ],
  },
  {
    major: 44,
    title: 'Passkeys and Keystore',
    summary: 'RakenOS 44 introduces passkeys, a hardware-backed keystore API for RAS apps, and system services rewritten in a memory-safe language.',
    notes: [
      'Security|Passkeys replace passwords for supporting websites and apps, and sync across your RakenOS devices end-to-end encrypted.',
      'Security|The keystore API lets RAS apps generate keys that never leave secure hardware where it is available.',
      'Security|Core system services such as the package manager and update agent are now written in a memory-safe language.',
      'Browser|Browser suggests creating a passkey when you sign up on a supporting website.',
      'Settings|The Passwords page lists passkeys and saved passwords with a security check for reused passwords.',
      'RAS Runtime|RAS API level 44 introduces the keystore and passkey APIs.',
    ],
    subjects: ['passkeys', 'the keystore API', 'memory-safe system services', 'the Passwords page'],
    s1: 'RakenOS 44.0.1 improves passkeys and the keystore.',
    f1: [
      'Security|Fixed an issue where a passkey created in the Browser could not be used in the matching RAS app.',
      'Settings|The Passwords page search now matches website names as well as addresses.',
    ],
    s2: 'RakenOS 44.0.2 strengthens security further.',
    f2: [
      'Security|Keystore keys can require user authentication for every use.',
      'Settings|The security check now warns about passwords that appeared in known data breaches.',
    ],
  },
  {
    major: 45,
    title: 'Computational Camera',
    summary: 'RakenOS 45 introduces a new computational photography pipeline, document scanning directly in Camera and stabilised video.',
    notes: [
      'Camera|The new imaging pipeline merges frames captured before you press the shutter for sharper photos with less noise.',
      'Camera|Document mode detects pages, corrects perspective and saves multi-page PDFs to Files.',
      'Camera|Video stabilisation uses motion data to keep handheld video smooth.',
      'Camera|Advanced camera hardware gains 10-bit video and a log profile for colour grading.',
      'Gallery|Text in photos can be selected and copied.',
      'Files|Scanned documents are searchable because text is recognised on the device.',
    ],
    subjects: ['the computational imaging pipeline', 'Document mode', 'video stabilisation', 'text selection in photos'],
    s1: 'RakenOS 45.0.1 improves image quality and document scanning.',
    f1: [
      'Camera|Improved edge detection for documents on light backgrounds.',
      'Camera|Fixed an issue where stabilised video could appear slightly cropped in the preview.',
    ],
    s2: 'RakenOS 45.0.2 polishes Camera and includes security fixes.',
    f2: [
      'Gallery|Recognised text can be translated on the device.',
      'Camera|Document mode can capture pages automatically when the device is held still.',
    ],
  },
  {
    major: 46,
    title: 'Home, Reimagined',
    summary: 'RakenOS 46 reimagines the Home Screen with Smart Folders, an App Library and free widget placement.',
    notes: [
      'Home Screen|Smart Folders organise apps automatically by category and keep the most used apps visible on the folder itself.',
      'Home Screen|The App Library lists every installed app alphabetically and by category on the last Home Screen page.',
      'Home Screen|Widgets and icons can be placed freely on the grid, leaving empty spaces where you want them.',
      'Home Screen|Pages can be hidden or reordered from the page overview.',
      'Search|Search suggests apps you might need based on time of day and routine.',
      'Settings|Choose whether newly installed apps appear on the Home Screen or only in the App Library.',
    ],
    subjects: ['Smart Folders', 'the App Library', 'free widget placement', 'the page overview'],
    s1: 'RakenOS 46.0.1 improves the reimagined Home Screen.',
    f1: [
      'Home Screen|Fixed an issue where empty grid spaces were filled after installing a new app.',
      'Home Screen|Smart Folders update their categories after an app changes category in Store.',
    ],
    s2: 'RakenOS 46.0.2 polishes the Home Screen and includes security fixes.',
    f2: [
      'Home Screen|The App Library supports scrolling by letter with a side index.',
      'Accessibility|Raken Narrator describes empty grid positions while editing the Home Screen.',
    ],
  },
  {
    major: 47,
    title: 'Adaptive Accessibility',
    summary: 'RakenOS 47 introduces Reading Assistant and Adaptive Touch, which learn how you interact with the device and adapt the interface to you.',
    notes: [
      'Accessibility|Reading Assistant highlights text as it is read aloud and can simplify layouts of long articles.',
      'Accessibility|Adaptive Touch learns how you tap and adjusts touch targets and hold durations accordingly.',
      'Accessibility|Hover Text shows a large-print version of any text under your finger.',
      'Accessibility|Personal Voice creates a synthesised voice from 15 minutes of recordings, processed on the device.',
      'Settings|Accessibility setup can be started from the first setup screen with a triple press.',
      'RAS Runtime|RAS API level 47 exposes semantic content regions for Reading Assistant.',
    ],
    subjects: ['Reading Assistant', 'Adaptive Touch', 'Hover Text', 'Personal Voice'],
    s1: 'RakenOS 47.0.1 improves adaptive accessibility features.',
    f1: [
      'Accessibility|Adaptive Touch adapts faster after switching between one-handed and two-handed use.',
      'Accessibility|Fixed an issue where Reading Assistant skipped image captions.',
    ],
    s2: 'RakenOS 47.0.2 polishes accessibility and includes security fixes.',
    f2: [
      'Accessibility|Hover Text can use a high-contrast colour scheme.',
      'Privacy|Personal Voice recordings can be deleted after the voice has been created.',
    ],
  },
  {
    major: 48,
    title: 'Lockdown and Protection',
    summary: 'RakenOS 48 introduces major security changes, including Lockdown mode, Advanced Data Protection and support for hardware security keys.',
    notes: [
      'Security|Lockdown mode drastically reduces attack surface for people who may be personally targeted, limiting attachments, link previews and connections.',
      'Security|Advanced Data Protection end-to-end encrypts every category of backup and sync data.',
      'Security|Hardware security keys can be used to protect your Raken Account.',
      'Security|Stolen Device Protection requires PIN and a one-hour delay for sensitive changes when away from familiar locations.',
      'Privacy|Link tracking parameters are removed from links in Browser, Notes and notifications.',
      'Settings|Security status summarises every protection with its current state and recommendation.',
    ],
    subjects: ['Lockdown mode', 'Advanced Data Protection', 'hardware security keys', 'Stolen Device Protection'],
    s1: 'RakenOS 48.0.1 refines the new protections.',
    f1: [
      'Security|Fixed an issue where Lockdown mode blocked fonts in some trusted RAS apps that were explicitly excluded.',
      'Settings|Stolen Device Protection shows the remaining delay time more clearly.',
    ],
    s2: 'RakenOS 48.0.2 strengthens security further.',
    f2: [
      'Security|Advanced Data Protection now also covers Routines and Focus configurations.',
      'Privacy|Tracking parameter removal handles several additional parameter formats.',
    ],
  },
  {
    major: 49,
    title: 'RScript 5',
    summary: 'RakenOS 49 introduces RScript 5 and RDesign 3. Type annotations, a new layout engine and live previews make building RAS apps faster and safer.',
    notes: [
      'RScript|RScript 5 adds optional type annotations that are checked when an app is packaged.',
      'RScript|Pattern matching with `match` simplifies handling of results, events and messages.',
      'Developer APIs|RDesign 3 introduces a constraint-free layout engine based on stacks, grids and adaptive spacing.',
      'Developer APIs|Live preview in Developer Studio renders RDesign layouts in light mode, dark mode and large text simultaneously.',
      'RAS Runtime|RAS API level 49 adds typed messages between app workers and system services.',
      'Performance|The RDesign 3 layout engine performs incremental layout, updating only changed parts of the interface.',
    ],
    subjects: ['RScript 5 type annotations', 'pattern matching', 'the RDesign 3 layout engine', 'incremental layout'],
    s1: 'RakenOS 49.0.1 improves RScript 5 and RDesign 3.',
    f1: [
      'RScript|Fixed an issue where type checking reported an error for valid nested map types.',
      'Developer APIs|RDesign 3 grids now distribute remaining space evenly between flexible columns.',
    ],
    s2: 'RakenOS 49.0.2 polishes the developer platform and includes security fixes.',
    f2: [
      'RScript|Error messages suggest the closest matching name for misspelled identifiers.',
      'Developer APIs|Live preview supports right-to-left layout.',
    ],
  },
  {
    major: 50,
    title: 'RakenOS 50',
    summary: 'RakenOS 50 marks the beginning of the most mature generation of RakenOS. A new modular system architecture allows individual system components to be updated independently, and the entire system has been refined for performance and stability.',
    notes: [
      'System|Modular system architecture: the interface, RAS runtime, Store, networking and security components can each be updated independently.',
      'System|A redesigned start sequence brings the device from power-on to the Lock Screen significantly faster.',
      'Performance|System-wide profiling guided optimisation of the 200 most frequently used code paths.',
      'Settings|System Update lists the version of each system component installed on the device.',
      'Security|Each system component is signed and verified separately, reducing the impact of any single vulnerability.',
      'Developer APIs|Apps can query the version of individual system components to enable features precisely.',
      'RAS Runtime|RAS API level 50 is a long-term API level supported by at least the next nine generations.',
    ],
    subjects: ['the modular system architecture', 'the redesigned start sequence', 'component-level updates', 'the long-term API level'],
    s1: 'RakenOS 50.0.1 refines the modular system architecture.',
    f1: [
      'System|Fixed an issue where an independently updated component was listed with its previous version until restart.',
      'Performance|Reduced start time after an update that changed only the interface component.',
    ],
    s2: 'RakenOS 50.0.2 polishes RakenOS 50 and includes security fixes.',
    f2: [
      'Settings|Component versions can be copied for support requests.',
      'Security|Component signatures are checked again after storage maintenance.',
    ],
  },
  {
    major: 51,
    title: 'Stability',
    summary: 'RakenOS 51 is dedicated to stability. A new system watchdog, crash recovery for system services and extensive fixes make RakenOS 51 the most reliable version so far.',
    notes: [
      'System|The system watchdog detects unresponsive services and restarts only the affected component, without restarting the device.',
      'System|The interface recovers from a crash in under a second, restoring the app you were using.',
      'System|Storage consistency checks run incrementally during idle time instead of at start.',
      'Settings|The new Diagnostics page shows system stability over the last 30 days, without personal data.',
      'Privacy|Sharing diagnostics with Raken is off by default and each report can be reviewed before it is sent.',
      'Bug Fixes|More than 400 issues reported by users across previous generations have been resolved.',
    ],
    subjects: ['the system watchdog', 'interface crash recovery', 'incremental storage checks', 'the Diagnostics page'],
    s1: 'RakenOS 51.0.1 continues the stability work.',
    f1: [
      'System|Fixed an issue where the watchdog could restart the Store service during a large download.',
      'Settings|The Diagnostics page loads faster on devices with long uptime.',
    ],
    s2: 'RakenOS 51.0.2 polishes RakenOS 51 and includes security fixes.',
    f2: [
      'Privacy|Diagnostics reports now show exactly which fields they contain.',
      'System|Improved recovery when the device runs out of storage during an app installation.',
    ],
  },
  {
    major: 52,
    title: 'Raken Design 3',
    summary: 'RakenOS 52 introduces Raken Design 3. Variable typography, adaptive density and a new icon family make the interface clearer and more comfortable across screen sizes.',
    notes: [
      'New|Raken Design 3 uses variable typography that adjusts weight and width for optimal legibility at every size.',
      'New|Adaptive density increases spacing on larger displays and tightens it on compact displays, without changing tap targets.',
      'New|A new system icon family with consistent stroke weights and optical balance.',
      'Settings|Appearance settings combine theme, accent colour, text size and density in one place with a live preview.',
      'Home Screen|App icons can be displayed in a tinted style that follows the accent colour.',
      'Accessibility|Bold Text uses dedicated heavier variable font instances instead of synthetic bold.',
      'Developer APIs|RDesign components adopt Raken Design 3 automatically, with density tokens for custom layouts.',
    ],
    subjects: ['Raken Design 3', 'variable typography', 'adaptive density', 'tinted app icons'],
    s1: 'RakenOS 52.0.1 fixes visual issues in Raken Design 3.',
    f1: [
      'Settings|Fixed an issue where the Appearance preview did not reflect the selected density.',
      'Home Screen|Tinted icons now keep sufficient contrast on light wallpapers.',
    ],
    s2: 'RakenOS 52.0.2 polishes Raken Design 3 and includes security fixes.',
    f2: [
      'Accessibility|Variable typography respects Bold Text in widgets.',
      'Control Center|Tile icons align optically with their labels.',
    ],
  },
  {
    major: 53,
    title: 'Predictive Performance',
    summary: 'RakenOS 53 makes the system anticipate what you need. Predictive app launch, storage compaction and a faster file system make everyday interactions quicker.',
    notes: [
      'Performance|Predictive app launch prepares the app you are most likely to open next, based on on-device patterns.',
      'Performance|Storage compaction runs during charging and reclaims space from fragmented app data.',
      'Performance|File system metadata operations are up to twice as fast, speeding up Files, Gallery and backups.',
      'Battery|Predictions are only computed while charging and require no network access.',
      'Settings|Storage settings show how much space compaction has recovered.',
      'Privacy|Predictive app launch can be switched off and its data cleared from Privacy settings.',
    ],
    subjects: ['predictive app launch', 'storage compaction', 'faster file system metadata', 'Storage settings'],
    s1: 'RakenOS 53.0.1 fine-tunes predictive performance.',
    f1: [
      'Performance|Predictive app launch no longer prepares apps that were removed from the Home Screen.',
      'Files|Fixed a delay when opening folders with many thousands of files.',
    ],
    s2: 'RakenOS 53.0.2 polishes performance and includes security fixes.',
    f2: [
      'Performance|Compaction pauses immediately when you start using the device.',
      'Settings|Storage recommendations include large, unused RAS app caches.',
    ],
  },
  {
    major: 54,
    title: 'Post-Quantum Security',
    summary: 'RakenOS 54 prepares for the future of cryptography with hybrid post-quantum key exchange for updates and sync, and RAS signature format 3.',
    notes: [
      'Security|System updates, Store downloads and sync use hybrid post-quantum key exchange combining ML-KEM and elliptic-curve cryptography.',
      'Security|RAS signature format 3 adds a post-quantum signature alongside the existing signature.',
      'Security|Packages signed with signature format 1 are no longer accepted for new installations.',
      'Developer APIs|The RAS signing tool can generate hybrid signing keys and migrate existing apps.',
      'Settings|Security status shows the cryptographic protection used for updates and sync.',
      'RAS Runtime|RAS API level 54 adds hybrid key agreement to the keystore API.',
    ],
    subjects: ['hybrid post-quantum key exchange', 'RAS signature format 3', 'signature migration', 'the updated keystore API'],
    s1: 'RakenOS 54.0.1 refines post-quantum security.',
    f1: [
      'Security|Fixed an issue where hybrid key exchange could fall back to classical mode on some networks.',
      'Raken Store|Apps awaiting signature migration are labelled clearly in the Library.',
    ],
    s2: 'RakenOS 54.0.2 strengthens security further.',
    f2: [
      'Security|Hybrid signatures are verified in constant time.',
      'Developer APIs|The signing tool reports which packages still use signature format 2.',
    ],
  },
  {
    major: 55,
    title: 'RAS Runtime 6',
    summary: 'RakenOS 55 introduces RAS Runtime 6 with capability-based permissions and WebAssembly modules inside RAS packages.',
    notes: [
      'RAS Runtime|Capability-based permissions grant apps narrowly scoped handles, such as one folder or one Bluetooth accessory, instead of broad permissions.',
      'RAS Runtime|RAS packages can include WebAssembly modules for performance-critical code, called from RScript.',
      'RScript|RScript 6 introduces immutable records and a `with` expression for updating them.',
      'Security|WebAssembly modules run inside the app worker with no direct system access.',
      'Privacy|The permission sheet shows exactly which resource an app will get access to.',
      'Developer APIs|Developer Studio profiles WebAssembly and RScript execution in one timeline.',
    ],
    subjects: ['capability-based permissions', 'WebAssembly modules', 'RScript records', 'scoped resource handles'],
    s1: 'RakenOS 55.0.1 refines RAS Runtime 6.',
    f1: [
      'RAS Runtime|Fixed an issue where a folder handle could not be restored after a backup restore.',
      'RScript|Records with many fields are compared faster.',
    ],
    s2: 'RakenOS 55.0.2 polishes RAS Runtime 6 and includes security fixes.',
    f2: [
      'Security|WebAssembly memory is cleared when an app moves to the hibernated state.',
      'Privacy|Unused resource handles are revoked after 30 days.',
    ],
  },
  {
    major: 56,
    title: 'Connectivity 3',
    summary: 'RakenOS 56 modernises connectivity with support for the latest Wi-Fi standards on capable hardware, precise sharing with ultra-wideband and a new Bluetooth stack.',
    notes: [
      'Connectivity|Multi-link Wi-Fi uses several frequency bands at once on supported hardware, for faster and more reliable connections.',
      'Connectivity|On devices with ultra-wideband hardware, Raken Beam shows the direction and distance of nearby devices.',
      'Connectivity|A rewritten Bluetooth stack improves audio quality and reconnection time for accessories.',
      'Connectivity|NFC tags can now trigger Routines on devices with NFC hardware.',
      'Control Center|The Connectivity panel shows signal quality and the active band for Wi-Fi.',
      'Battery|The new Bluetooth stack reduces power use with LE Audio accessories.',
    ],
    subjects: ['multi-link Wi-Fi', 'ultra-wideband sharing', 'the rewritten Bluetooth stack', 'NFC Routine triggers'],
    s1: 'RakenOS 56.0.1 improves wireless reliability.',
    f1: [
      'Connectivity|Fixed an issue where some Bluetooth keyboards reconnected with a delay after wake.',
      'Connectivity|Multi-link Wi-Fi recovers faster when one band becomes unavailable.',
    ],
    s2: 'RakenOS 56.0.2 polishes connectivity and includes security fixes.',
    f2: [
      'Security|Bluetooth pairing now shows the accessory type verified from its advertised services.',
      'Connectivity|NFC Routine triggers can require the device to be unlocked.',
    ],
  },
  {
    major: 57,
    title: 'Priority Notifications',
    summary: 'RakenOS 57 introduces Priority Inbox for notifications and Focus summaries that help you catch up on what matters.',
    notes: [
      'Notifications|Priority Inbox places the notifications most likely to need your attention at the top, ranked on the device.',
      'Notifications|Focus summaries condense what happened during a Focus into a short list of highlights.',
      'Notifications|Mark a notification "Not important" to teach Priority Inbox what matters to you.',
      'Lock Screen|The Lock Screen shows Priority Inbox items first, with the rest collapsed.',
      'Privacy|Priority ranking runs entirely on the device and can be reset at any time.',
      'RAS Runtime|RAS API level 57 lets apps provide a relevance hint for each notification.',
    ],
    subjects: ['Priority Inbox', 'Focus summaries', 'notification relevance hints', 'Lock Screen priority ordering'],
    s1: 'RakenOS 57.0.1 improves Priority Inbox.',
    f1: [
      'Notifications|Fixed an issue where a time-sensitive notification could be ranked below routine notifications.',
      'Notifications|Focus summaries are ready immediately when a Focus ends.',
    ],
    s2: 'RakenOS 57.0.2 polishes notifications and includes security fixes.',
    f2: [
      'Notifications|Priority Inbox can be limited to selected apps.',
      'Accessibility|Focus summaries are read in priority order by Raken Narrator.',
    ],
  },
  {
    major: 58,
    title: 'System Architecture',
    summary: 'RakenOS 58 splits the remaining system services into isolated components, reducing update sizes and improving resilience.',
    notes: [
      'System|The remaining monolithic system services have been split into 34 isolated components with minimal privileges.',
      'System|System updates now contain only changed components, reducing typical update size by up to 70%.',
      'Security|Each component runs with its own identity, so a fault in one component cannot access data of another.',
      'Performance|Components start on demand, lowering idle memory use.',
      'Settings|System Update shows the download size of each component in an update.',
      'Developer APIs|The system services map in Developer options shows which component provides each API.',
    ],
    subjects: ['isolated system components', 'component-only updates', 'per-component identities', 'on-demand component start'],
    s1: 'RakenOS 58.0.1 refines the new system architecture.',
    f1: [
      'System|Fixed an issue where a component started on demand could delay the first notification after unlock.',
      'Settings|Component download sizes are now shown before the update starts downloading.',
    ],
    s2: 'RakenOS 58.0.2 polishes the architecture and includes security fixes.',
    f2: [
      'Security|Component identities are rotated during every system update.',
      'Performance|Frequently used components stay resident when memory allows.',
    ],
  },
  {
    major: 59,
    title: 'The Mature Generation',
    summary: 'RakenOS 59 is the culmination of the most mature generation of RakenOS. It refines every part of the system, extends long-term support and brings the design, runtime, security and architecture work of previous generations together.',
    notes: [
      'New|Long-term support: RakenOS 59 receives security updates for an extended period on every compatible device.',
      'Home Screen|The Home Screen, Lock Screen and Control Center share a single motion and layout model for fully consistent behaviour.',
      'System|Update planning downloads upcoming components ahead of time and applies them in one restart.',
      'RAS Runtime|RAS API level 59 finalises the long-term API surface introduced in RakenOS 50.',
      'RScript|RScript 6.9 improves error messages, formatting tools and runtime diagnostics.',
      'Security|The security model is documented in the new Security Guide available from About RakenOS.',
      'Accessibility|Every system screen has been audited for Raken Narrator, Voice Control and large text.',
      'Performance|The system has been profiled end to end on every compatible device configuration.',
    ],
    subjects: ['the unified motion model', 'update planning', 'the Security Guide', 'long-running device maintenance'],
    s1: 'RakenOS 59.0.1 refines the final generation of the current architecture.',
    f1: [
      'System|Fixed an issue where update planning downloaded a component that was already installed.',
      'Accessibility|Improved focus order in the Security Guide.',
    ],
    s2: 'RakenOS 59.0.2 is the latest release of RakenOS, focusing on polish, stability and security.',
    f2: [
      'Security|Updated trusted certificate authorities used by system services.',
      'System|Improved reliability of long-running devices that are rarely restarted.',
    ],
  },
];
