'use strict';
// Maintenance content pools used by the release generator for .0.1 and .0.2
// releases. Every pool entry is used at most once across the entire history,
// so no two releases share the same sentence.
//
// Entry format: [section, text, minMajor?, maxMajor?]

// Templates that target what a generation introduced. `{s}` is replaced with
// a subject from the generation (for example "widget stacks").
const subjectTemplates = {
  // Used in .0.1 releases (stability and corrections).
  stability: [
    ['Bug Fixes', 'Fixed an issue affecting {s} after the device resumed from sleep.'],
    ['Bug Fixes', 'Fixed a rare crash related to {s} when storage was almost full.'],
    ['Bug Fixes', 'Resolved an issue where preferences for {s} were not restored after a restart.'],
    ['Bug Fixes', 'Fixed an issue where {s} showed outdated text after changing the system language.'],
    ['Bug Fixes', 'Fixed a layout issue in {s} when the display size setting was changed.'],
    ['Bug Fixes', 'Fixed an issue where {s} could briefly use the wrong colour scheme when switching between light and dark mode.'],
    ['System', 'Improved the reliability of {s} when switching quickly between apps.'],
    ['System', 'Improved error recovery for {s} after an unexpected restart of a system service.'],
    ['System', 'Improved diagnostics for {s} to help identify rare failures, without collecting personal data.'],
    ['Performance', 'Reduced start-up work for {s} after unlocking.'],
    ['Performance', 'Reduced memory use related to {s} by avoiding redundant layout passes.'],
    ['Battery', 'Reduced background power use associated with {s}.'],
  ],
  // Used in .0.2 releases (polish, accessibility and security hardening).
  polish: [
    ['Accessibility', 'Improved screen reader labels for {s}.', 1, 11],
    ['Accessibility', 'Raken Narrator now describes {s} more precisely.', 12],
    ['Accessibility', 'Text related to {s} now scales correctly with the largest text sizes.', 12],
    ['Accessibility', 'Improved focus order when navigating {s} with a keyboard.'],
    ['Performance', 'Smoother animations related to {s} on displays with a high refresh rate.'],
    ['Settings', 'Added a short explanation of {s} to the corresponding Settings page.'],
    ['Settings', 'Options for {s} can now be found through Settings search.', 9],
    ['Privacy', 'The privacy information sheet now explains which data {s} uses and where it is stored.', 5],
    ['Battery', 'Background work related to {s} now pauses while Battery Saver is active.', 7],
    ['Bug Fixes', 'Refined spacing and alignment related to {s} for right-to-left languages.'],
    ['Bug Fixes', 'Refined the wording of messages related to {s}.'],
  ],
};

// One-off maintenance notes that fit a range of generations.
const pool = [
  // Home Screen
  ['Home Screen', 'Icons no longer jump briefly to a new position when an app finishes installing.'],
  ['Home Screen', 'Improved the accuracy of long-press detection on app icons near the edge of the screen.'],
  ['Home Screen', 'Fixed an issue where the page indicator could show the wrong page after unlocking.'],
  ['Home Screen', 'App names that are too long now fade out instead of being cut mid-letter.'],
  ['Home Screen', 'Fixed an issue where the Home Screen could scroll horizontally while dragging a widget vertically.', 11],
  ['Home Screen', 'The dock keeps its background blur consistent when the wallpaper changes.'],
  ['Home Screen', 'Improved drag feedback when moving an icon into a full dock.'],
  ['Home Screen', 'Fixed an issue where removing an app left an empty space until the next restart.'],
  ['Home Screen', 'Badge counts on app icons update immediately when notifications are cleared.'],
  ['Home Screen', 'Fixed an issue where the Clock widget skipped a minute after waking from deep sleep.'],
  ['Home Screen', 'Home Screen edit mode can now be exited with the back gesture.'],
  ['Home Screen', 'Improved legibility of app names over very light wallpapers.'],
  ['Home Screen', 'Fixed an issue where Recent Apps previews appeared blank for apps using dark mode.', 10],
  ['Home Screen', 'Fixed an issue where the last row of the app grid could be hidden behind the dock on compact displays.'],
  ['Home Screen', 'Opening a folder while an app is still animating closed is now handled correctly.'],
  ['Home Screen', 'Improved the gesture bar threshold so that swiping home is less likely to be triggered accidentally.'],
  // Lock Screen
  ['Lock Screen', 'The PIN keypad responds faster to the first touch after the display wakes.'],
  ['Lock Screen', 'Fixed an issue where the date could use the wrong language after changing region settings.'],
  ['Lock Screen', 'The camera shortcut now opens reliably when pressed during the unlock animation.'],
  ['Lock Screen', 'The battery percentage on the Lock Screen now updates while charging wirelessly.'],
  ['Lock Screen', 'Fixed an issue where the lockout timer could restart after an incorrect PIN was entered twice quickly.'],
  ['Lock Screen', 'Improved contrast of the clock over bright wallpapers.'],
  ['Lock Screen', 'Swiping up to unlock now follows the finger more closely.'],
  ['Lock Screen', 'Fixed an issue where the flashlight shortcut stayed highlighted after the flashlight was switched off.'],
  ['Lock Screen', 'Emergency information is now accessible when the device is locked out after incorrect PIN attempts.'],
  ['Lock Screen', 'Media controls on the Lock Screen now show the correct artwork after switching tracks.', 3],
  // Notifications
  ['Notifications', 'Notifications with long titles now wrap to two lines instead of being truncated.'],
  ['Notifications', 'Fixed an issue where dismissing a group of notifications could leave one behind.'],
  ['Notifications', 'Notification actions respond more reliably when tapped while the list is scrolling.'],
  ['Notifications', 'Fixed an issue where notification sounds played while Do Not Disturb was on.'],
  ['Notifications', 'Clear All now asks for confirmation when more than 20 notifications are present.'],
  ['Notifications', 'Improved ordering of notifications that arrive at the same second.'],
  ['Notifications', 'Fixed an issue where notification timestamps were not updated while the Notification Center was open.'],
  ['Notifications', 'Notifications from removed apps are now removed from the Notification Center automatically.'],
  ['Notifications', 'Expanded notifications now collapse when the Notification Center is closed.'],
  ['Notifications', 'Improved rendering of notifications that include large images.'],
  ['Notifications', 'Fixed an issue where snoozed notifications lost their action buttons.', 3],
  ['Notifications', 'Live Status items no longer flicker when updated frequently.', 23],
  // Control Center
  ['Control Center', 'The brightness slider now changes the display brightness smoothly without steps.'],
  ['Control Center', 'Fixed an issue where the Wi-Fi tile showed "Connecting" after the connection had been established.'],
  ['Control Center', 'Control Center can now be closed by tapping the empty area below the tiles.'],
  ['Control Center', 'The volume slider reflects changes made with hardware buttons immediately.'],
  ['Control Center', 'Fixed an issue where tile order was reset after a system update.'],
  ['Control Center', 'The flashlight tile is only shown when a flashlight is detected on the device.'],
  ['Control Center', 'Improved haptic feedback when toggling tiles.'],
  ['Control Center', 'Fixed an issue where Airplane mode did not turn off Bluetooth when it had been enabled manually.'],
  ['Control Center', 'Long-pressing a tile now opens its settings more quickly.', 3],
  // Camera
  ['Camera', 'Improved autofocus when tapping near the edge of the viewfinder.'],
  ['Camera', 'Fixed an issue where the first photo after opening Camera could be slightly overexposed.'],
  ['Camera', 'The viewfinder now resumes faster after returning from Gallery.'],
  ['Camera', 'Improved colour accuracy of skin tones under warm lighting.'],
  ['Camera', 'Fixed an issue where the grid overlay remained visible in recorded videos.'],
  ['Camera', 'The shutter button is now disabled while a photo is being saved, preventing duplicate captures.'],
  ['Camera', 'Fixed an issue where zoom was reset after switching between photo and video.'],
  ['Camera', 'Improved exposure stability when panning slowly across a bright window.'],
  ['Camera', 'Photos captured in portrait orientation are rotated correctly on older external viewers.'],
  ['Camera', 'Reduced shutter lag on devices with advanced camera hardware.', 15],
  ['Camera', 'Night mode now cancels cleanly if the device detects significant movement.', 15],
  // Gallery
  ['Gallery', 'Scrolling through large photo libraries is smoother.'],
  ['Gallery', 'Fixed an issue where deleted photos remained visible in search results.'],
  ['Gallery', 'Pinch to zoom in the photo viewer now zooms towards the centre of the pinch.'],
  ['Gallery', 'Improved thumbnail quality for panoramic photos.'],
  ['Gallery', 'Fixed an issue where the photo count of an album was incorrect after moving photos.', 2],
  ['Gallery', 'Photos can now be deleted directly from the viewer with an undo option.'],
  ['Gallery', 'The information panel shows the file size and resolution of each photo.'],
  ['Gallery', 'Fixed an issue where the edit toolbar overlapped the gesture bar in landscape.', 4],
  ['Gallery', 'Recently Deleted keeps photos for 30 days with a clear countdown.'],
  // Files
  ['Files', 'Copying large files now shows a more accurate time estimate.'],
  ['Files', 'Fixed an issue where file sizes over 4 GB were displayed incorrectly.'],
  ['Files', 'Sorting by name now handles numbers naturally, so "file10" comes after "file9".'],
  ['Files', 'Fixed an issue where the Downloads folder did not refresh after a download completed.'],
  ['Files', 'Improved icons for common document types.'],
  ['Files', 'Moving files between folders now preserves their modification date.'],
  ['Files', 'Fixed an issue where a folder could not be renamed to a name that differed only in capitalisation.'],
  ['Files', 'Deleting many files at once is significantly faster.'],
  ['Files', 'Previews of text files now use the system monospaced font.'],
  ['Files', 'Tag filters are remembered for each location.', 2],
  // Raken Store
  ['Raken Store', 'Search results now show the app size and compatibility before you open the app page.'],
  ['Raken Store', 'Fixed an issue where the Install button could show "Open" before installation had completed.'],
  ['Raken Store', 'Improved download resumption on unstable connections.'],
  ['Raken Store', 'Screenshots on app pages now load at a resolution suited to the display.'],
  ['Raken Store', 'The Library can be sorted by name, install date or last opened.'],
  ['Raken Store', 'Fixed an issue where categories showed apps that are not compatible with the device.'],
  ['Raken Store', 'App pages now show the minimum RakenOS version required.'],
  ['Raken Store', 'Improved error messages when a RAS package requires a capability that is not available on this device.'],
  ['Raken Store', 'Updates in the Library are listed with their release notes.', 6],
  ['Raken Store', 'Fixed an issue where an app update could remain queued after cancelling another download.', 6],
  ['Raken Store', 'Search now tolerates common typing mistakes in app names.'],
  ['Raken Store', 'The permission summary on app pages groups permissions by purpose.', 5],
  // Browser
  ['Browser', 'Pages restore their scroll position when you return to a tab.'],
  ['Browser', 'Fixed an issue where downloads from the Browser did not appear in Files.'],
  ['Browser', 'The address bar shows the full address when editing, and only the domain otherwise.'],
  ['Browser', 'Improved text rendering on pages with custom fonts.'],
  ['Browser', 'Fixed an issue where video continued playing after closing a tab.'],
  ['Browser', 'Bookmarks can be reordered by dragging.'],
  ['Browser', 'Reduced memory use of inactive tabs.'],
  ['Browser', 'Pull to refresh now works on pages that scroll within a frame.'],
  ['Browser', 'Fixed an issue where Reader mode lost its font setting after a restart.', 28],
  // Settings
  ['Settings', 'Settings now opens directly at the last visited page when reopened within a few minutes.'],
  ['Settings', 'Fixed an issue where toggles could briefly show the wrong state when opening a page.'],
  ['Settings', 'Improved layout of Settings on compact displays.'],
  ['Settings', 'The About page shows the time since the last restart.'],
  ['Settings', 'Fixed an issue where the Display page did not reflect a change made in Control Center.'],
  ['Settings', 'Sound settings play a short preview when a notification sound is selected.'],
  ['Settings', 'Developer options remember their expanded sections.'],
  ['Settings', 'Fixed an issue where the storage summary took a long time to calculate.'],
  ['Settings', 'Wallpaper previews now show the Home Screen and Lock Screen side by side.'],
  // Accessibility
  ['Accessibility', 'Buttons in system dialogs now have larger touch targets when Bold Text is enabled.'],
  ['Accessibility', 'Improved contrast of placeholder text in search fields.'],
  ['Accessibility', 'Focus indicators are now visible on every Control Center tile.'],
  ['Accessibility', 'Haptic feedback can be set to stronger intensity for users with reduced sensitivity.'],
  ['Accessibility', 'Captions are now available for system tutorial videos.'],
  ['Accessibility', 'Mono audio setting now applies to all audio outputs.'],
  ['Accessibility', 'Raken Narrator reads the battery percentage when the status bar is focused.', 12],
  ['Accessibility', 'Improved Magnifier tracking when typing in text fields.', 12],
  ['Accessibility', 'Colour filters are no longer applied twice in Split View.', 12],
  ['Accessibility', 'Voice Control recognises app names with numbers more reliably.', 43],
  ['Accessibility', 'Switch Control scanning speed can be adjusted in finer steps.', 43],
  // Privacy
  ['Privacy', 'Location access indicators now appear in Control Center as well as the status bar.'],
  ['Privacy', 'Screenshots no longer include content from windows marked as sensitive.'],
  ['Privacy', 'The rollout identifier used for staged system updates can now be reset in Privacy settings.'],
  ['Privacy', 'Diagnostics that you choose to share no longer include app names.'],
  ['Privacy', 'Apps must now explain why they need access to Bluetooth before the permission sheet is shown.', 5],
  ['Privacy', 'Search history is excluded from backups unless you choose to include it.', 14],
  ['Privacy', 'The Privacy dashboard now shows access by RAS widgets separately.', 11],
  ['Privacy', 'Recently used permission prompts are listed in the Privacy dashboard.', 5],
  // Battery
  ['Battery', 'Improved accuracy of the battery percentage at low charge levels.'],
  ['Battery', 'Reduced power use while the device is idle with Wi-Fi enabled.'],
  ['Battery', 'The battery usage list now includes the system update service.'],
  ['Battery', 'Charging notifications now show the charging speed.'],
  ['Battery', 'Reduced power consumption of the Lock Screen clock when it is displayed for long periods.'],
  ['Battery', 'Background location requests are batched more efficiently.'],
  ['Battery', 'Fixed an issue where Battery Saver turned off by itself after charging to 80%.', 7],
  ['Battery', 'Battery usage history is preserved across system updates.', 7],
  // Performance
  ['Performance', 'Faster opening of Settings subpages with many rows.'],
  ['Performance', 'Reduced start-up time of built-in apps by loading icons asynchronously.'],
  ['Performance', 'Improved scrolling performance in long lists across the system.'],
  ['Performance', 'Faster restoration of apps from Recent Apps.'],
  ['Performance', 'Reduced input latency when typing in Notes.'],
  ['Performance', 'The Notification Center opens faster when many notifications are present.'],
  ['Performance', 'Reduced system storage usage by removing obsolete caches after updates.'],
  ['Performance', 'Faster boot after a system update by precompiling system components.'],
  // Connectivity
  ['Connectivity', 'Improved reconnection to Wi-Fi networks after the device wakes from sleep.'],
  ['Connectivity', 'Fixed an issue where Bluetooth headphones reconnected with low audio quality.'],
  ['Connectivity', 'Captive portal pages for public Wi-Fi now open automatically.'],
  ['Connectivity', 'Improved stability of Bluetooth connections with multiple accessories.'],
  ['Connectivity', 'Fixed an issue where mobile data stayed off after turning Airplane mode off.'],
  ['Connectivity', 'The Wi-Fi list refreshes more quickly when opening Wi-Fi settings.'],
  ['Connectivity', 'NFC tags are read more reliably when held briefly near the device.', 8],
  ['Connectivity', 'Raken Beam finds nearby devices faster when both screens are on.', 8],
  // System
  ['System', 'Improved stability when many apps are installed at the same time.'],
  ['System', 'Improved handling of time zone changes during daylight saving transitions.'],
  ['System', 'Fixed an issue where the device could take longer to restart when storage was nearly full.'],
  ['System', 'System services now shut down in a safer order during restart.'],
  ['System', 'Improved detection of hardware capabilities at start-up.'],
  ['System', 'Improved recovery when the device is restarted during a RAS app installation.'],
  ['System', 'The system update service now retries failed downloads with increasing delays.'],
  ['System', 'Fixed an issue where the system clock could drift after long periods without a network connection.'],
  ['System', 'Improved reliability of scheduled tasks after the device is restarted.'],
  // Developer APIs
  ['Developer APIs', 'The notification API now reports why a notification was not shown.', 3],
  ['Developer APIs', 'Capability queries return results synchronously after the first call.'],
  ['Developer APIs', 'Storage quota errors now include the remaining space available to the app.'],
  ['Developer APIs', 'New developer option to simulate a missing hardware capability for testing.'],
  ['Developer APIs', 'The package validator now reports all manifest errors at once instead of stopping at the first.'],
  ['Developer APIs', 'Lifecycle events are delivered in a consistent order when the device locks.', 16],
  ['Developer APIs', 'Widget timelines can now be refreshed on demand from the app.', 11],
  // RAS Runtime
  ['RAS Runtime', 'Improved start-up time for RAS apps with many assets.'],
  ['RAS Runtime', 'RAS apps now receive a clear error when they exceed their storage quota.'],
  ['RAS Runtime', 'Fixed an issue where a RAS app could not read its own assets after being moved to external storage.', 19],
  ['RAS Runtime', 'Improved isolation between RAS apps sharing the same developer.'],
  ['RAS Runtime', 'Permissions declared as optional are now requested only when first used.'],
  ['RAS Runtime', 'Improved compatibility of RAS packages built with earlier versions of the packaging tools.'],
  ['RAS Runtime', 'RAS apps that crash repeatedly on launch are now reported in Settings with an option to reinstall.'],
  // RScript
  ['RScript', 'String concatenation in loops is significantly faster.'],
  ['RScript', 'Improved error messages for calls to undefined functions.'],
  ['RScript', 'Fixed an issue where comparison of negative decimal numbers could return an incorrect result.'],
  ['RScript', 'List functions `map`, `filter` and `reduce` are faster for large lists.'],
  ['RScript', 'Stack traces now include the name of the RAS package and source file.'],
  ['RScript', 'Reduced memory allocations when formatting numbers and dates.'],
  ['RScript', 'Fixed an issue where deeply nested maps could not be serialised to storage.'],
  // Later generations
  ['Home Screen', 'Smart Folder previews now update when an app inside the folder shows a new badge.', 46],
  ['Home Screen', 'The App Library index responds faster when scrolling quickly through letters.', 46],
  ['Home Screen', 'Widget stacks remember their last shown widget after a restart.', 11],
  ['Home Screen', 'Improved the layout of free-placed widgets when switching between compact and regular display sizes.', 46],
  ['Home Screen', 'Opening an app from a Smart Folder now animates from the folder preview.', 46],
  ['Lock Screen', 'Lock Screen widgets refresh immediately after the device is unlocked once.', 27],
  ['Lock Screen', 'Improved legibility of the Focus indicator on Lock Screens with a depth effect.', 27],
  ['Lock Screen', 'Linked Lock Screens now switch without a visible flash when a Focus starts.', 27],
  ['Notifications', 'Priority Inbox rankings are recalculated faster after marking a notification as not important.', 57],
  ['Notifications', 'Notification summaries now respect the 24-hour time setting.', 23],
  ['Notifications', 'Notification channels created by an app are listed in the order the app declares them.', 23],
  ['Control Center', 'The Connectivity panel refreshes signal information more frequently while it is open.', 56],
  ['Control Center', 'Tile animations stay in sync with the finger during fast swipes.', 41],
  ['Camera', 'Document mode handles pages with folded corners more accurately.', 45],
  ['Camera', '10-bit video recordings now show the correct remaining recording time.', 45],
  ['Camera', 'Improved frame alignment in low-light photos of moving subjects.', 45],
  ['Gallery', 'Text recognised in photos can now be searched from Universal Search.', 45],
  ['Gallery', 'Improved performance of the editor when adjusting RAW photos.', 15],
  ['Files', 'Shared folder activity now loads incrementally for folders with long histories.', 35],
  ['Files', 'Secure Folder unlocks faster on devices with many protected files.', 36],
  ['Files', 'Component-only updates no longer leave temporary files in system storage.', 58],
  ['Raken Store', 'Subscription renewal reminders arrive three days before renewal instead of one.', 42],
  ['Raken Store', 'The Optimising status after downloading an app now shows its progress.', 40],
  ['Raken Store', 'Verified developer badges are shown in search results as well as on app pages.', 42],
  ['Raken Store', 'Apps using signature format 3 are installed without an additional verification step.', 54],
  ['Browser', 'Passkey sign-in sheets appear faster on supporting websites.', 44],
  ['Browser', 'Tab groups can be renamed from the tab overview.', 28],
  ['Browser', 'Tracker blocking no longer breaks embedded video players on some news sites.', 28],
  ['Settings', 'The Component Versions list in System Update can be sorted by name or last update.', 50],
  ['Settings', 'Appearance settings preview the selected density on the Lock Screen as well as the Home Screen.', 52],
  ['Settings', 'The Diagnostics page shows the number of recovered service interruptions.', 51],
  ['Settings', 'Storage settings show the space used by WebAssembly caches.', 55],
  ['Accessibility', 'Reading Assistant now continues reading across pages in Reader mode.', 47],
  ['Accessibility', 'Live Captions can use a larger font without covering controls.', 43],
  ['Accessibility', 'Adaptive Touch settings are included in encrypted backups.', 47],
  ['Privacy', 'The App Privacy Report can be exported as a document to Files.', 32],
  ['Privacy', 'Resource handles granted to apps are listed per app in Privacy settings.', 55],
  ['Privacy', 'Predictive app launch data is excluded from backups.', 53],
  ['Security', 'Updated the list of revoked RAS developer keys.'],
  ['Security', 'Stolen Device Protection now also covers changes to Private Space settings.', 48],
  ['Security', 'The sandbox now denies access to unused hardware sensors by default.', 25],
  ['Battery', 'Storage compaction now pauses when the battery temperature rises.', 53],
  ['Battery', 'Reduced power use of the system watchdog during standby.', 51],
  ['Battery', 'Multi-link Wi-Fi uses a single band when the device is idle to save power.', 56],
  ['Performance', 'Bytecode for frequently used RAS apps stays cached across system updates.', 40],
  ['Performance', 'On-demand components start faster when the device is under memory pressure.', 58],
  ['Performance', 'Incremental layout is now used for RDesign lists with thousands of rows.', 49],
  ['Performance', 'Reduced the time between restart and the first frame of the Lock Screen.', 50],
  ['Connectivity', 'Handoff works more reliably between devices on different Wi-Fi bands.', 22],
  ['Connectivity', 'Ultra-wideband direction indicators are more stable when the device is moving.', 56],
  ['System', 'Update planning now avoids downloading components while the device is on a metered connection.', 59],
  ['System', 'Improved recovery when a component update is interrupted by a power loss.', 50],
  ['System', 'The watchdog now records which component recovered in the Diagnostics page.', 51],
  ['System', 'Seamless updates verify the inactive slot again just before restarting.', 37],
  ['Developer APIs', 'Memory pressure hints are now delivered to apps in Split View.', 21],
  ['Developer APIs', 'Typed messages report schema mismatches with the field name.', 49],
  ['Developer APIs', 'Component version queries are available from RScript without an additional permission.', 50],
  ['RAS Runtime', 'WebAssembly modules can now be loaded lazily on first use.', 55],
  ['RAS Runtime', 'App workers restart faster after a crash, restoring the last saved state.', 40],
  ['RAS Runtime', 'Capability handles are restored correctly after moving an app into Private Space.', 55],
  ['RScript', 'Pattern matching on nested records is faster.', 55],
  ['RScript', 'The formatter keeps comments attached to the correct statement.', 49],
  ['RScript', 'Type annotations on async functions are now checked correctly.', 49],
  ['RScript', 'Module import cycles are reported with the full import chain.', 40],
  // Bug Fixes (general)
  ['Bug Fixes', 'Fixed an issue where the status bar clock did not update immediately after changing the time format.'],
  ['Bug Fixes', 'Fixed an issue where the keyboard could cover the search field in Settings.'],
  ['Bug Fixes', 'Fixed an issue where dark mode was not applied to some system dialogs.'],
  ['Bug Fixes', 'Fixed an issue where the device vibrated twice for a single notification.'],
  ['Bug Fixes', 'Fixed an issue where copied text lost its line breaks when pasted into Notes.'],
  ['Bug Fixes', 'Fixed an issue where the Calculator displayed rounding errors for some decimal operations.'],
  ['Bug Fixes', 'Fixed an issue where the stopwatch continued counting after being reset while the screen was off.'],
  ['Bug Fixes', 'Fixed an issue where system sounds played at full volume after a restart.'],
  ['Bug Fixes', 'Fixed an issue where some sheets could not be dismissed with a downward swipe.'],
  ['Bug Fixes', 'Fixed an issue where long file names overflowed dialog boxes.'],
  ['Bug Fixes', 'Fixed an issue where the rotation lock setting was ignored by some system apps.'],
  ['Bug Fixes', 'Fixed an issue where alarms could sound silently when headphones were disconnected.'],
];

// Security advisory building blocks. Each advisory is generated at most once.
const securityComponents = [
  { name: 'the RAS package validator', min: 1, impacts: ['a malformed package to be installed without complete validation', 'a crafted package to cause the installer to stop responding'] },
  { name: 'the RScript interpreter', min: 1, impacts: ['a malicious RAS app to read memory outside its sandbox', 'a crafted script to cause unexpected termination of the app worker'] },
  { name: 'the image decoder', min: 1, impacts: ['a crafted image to cause unexpected app termination', 'a crafted image to read limited memory contents'] },
  { name: 'the notification service', min: 1, impacts: ['an app to read notification content from other apps', 'notification content to appear on the Lock Screen despite privacy settings'] },
  { name: 'the Lock Screen', min: 1, impacts: ['a person with physical access to open Control Center settings without unlocking', 'the PIN lockout delay to be bypassed'] },
  { name: 'the Wi-Fi service', min: 1, impacts: ['an attacker on the same network to cause a denial of service', 'an app to determine nearby network names without permission'] },
  { name: 'the Bluetooth stack', min: 1, impacts: ['a nearby attacker to cause a denial of service', 'a nearby attacker to pair without confirmation'] },
  { name: 'the Browser engine', min: 1, impacts: ['a crafted website to execute arbitrary code', 'a crafted website to access data from another origin'] },
  { name: 'the font renderer', min: 1, impacts: ['a crafted font to cause unexpected termination', 'a crafted document to read limited memory contents'] },
  { name: 'the update agent', min: 1, impacts: ['a network attacker to delay an available system update', 'a local app to interfere with update verification'] },
  { name: 'the Files service', min: 2, impacts: ['an app with access to one file to access other files in the same folder', 'a crafted file name to break out of the destination folder'] },
  { name: 'the media playback service', min: 3, impacts: ['a crafted audio file to cause unexpected termination', 'an app to control media playback of another app'] },
  { name: 'the permission service', min: 5, impacts: ['a one-time permission to persist after the app was closed', 'an app to bypass the permission rationale sheet'] },
  { name: 'Raken Beam', min: 8, impacts: ['a nearby device to send files without confirmation', 'a nearby attacker to learn the device name while Beam was disabled'] },
  { name: 'the NFC service', min: 8, impacts: ['a crafted tag to open a link without confirmation', 'a crafted tag to cause the NFC service to restart'] },
  { name: 'the widget renderer', min: 11, impacts: ['a widget to display content from another app', 'a crafted widget layout to cause excessive memory use'] },
  { name: 'the search indexer', min: 14, impacts: ['an app to query content from the search index of another app', 'indexed content from Private Space to appear in search'] },
  { name: 'the scanner service', min: 17, impacts: ['an app to receive scan results intended for another app', 'a crafted barcode to cause the scanner service to stop responding'] },
  { name: 'the continuity service', min: 22, impacts: ['a removed device to receive Handoff activity', 'Universal Clipboard content to persist longer than intended'] },
  { name: 'the secure storage service', min: 24, impacts: ['an app to read secure storage entries after reinstallation of another app', 'secure storage to be accessed before first unlock'] },
  { name: 'the sandbox broker', min: 25, impacts: ['a malicious app to call undeclared system services', 'a sandboxed app to escalate its privileges'] },
  { name: 'the sync service', min: 29, impacts: ['sync data to be sent to a device that had been removed', 'a server-side attacker to replay an old sync record'] },
  { name: 'the backup service', min: 33, impacts: ['backup contents to be restored without verifying the PIN', 'a partially written backup to be treated as complete'] },
  { name: 'the Routines engine', min: 34, impacts: ['a routine created by an app to run without approval', 'a routine to access location while location services were disabled'] },
  { name: 'Private Space', min: 36, impacts: ['Private Space app names to appear in Recent Apps', 'Private Space notifications to be visible after locking'] },
  { name: 'the bytecode verifier', min: 40, impacts: ['a malformed bytecode module to be executed', 'a crafted module to read outside its heap'] },
  { name: 'the keystore', min: 44, impacts: ['a key requiring authentication to be used without authentication', 'an app to enumerate key aliases of another app'] },
  { name: 'the WebAssembly runtime', min: 55, impacts: ['a crafted module to read memory outside its linear memory', 'a crafted module to stall the app worker'] },
  { name: 'the component loader', min: 50, impacts: ['an unsigned component to be loaded after storage maintenance', 'a component to be downgraded to a vulnerable version'] },
];

// Vulnerability classes, each with the kinds of fix that match it.
const securityClasses = [
  { name: 'a memory corruption issue', fixes: ['with improved memory handling', 'with improved bounds checking'] },
  { name: 'an out-of-bounds read', fixes: ['with improved bounds checking', 'with improved input validation'] },
  { name: 'a logic issue', fixes: ['with improved checks', 'with improved state handling', 'by removing the vulnerable code'] },
  { name: 'a race condition', fixes: ['with improved locking', 'with improved state handling'] },
  { name: 'a permissions issue', fixes: ['with additional permission checks', 'with additional restrictions'] },
  { name: 'an input validation issue', fixes: ['with improved input validation', 'with stricter parsing'] },
  { name: 'a use-after-free issue', fixes: ['with improved memory management', 'with improved object lifetime tracking'] },
  { name: 'an integer overflow', fixes: ['with improved bounds checking', 'with improved input validation'] },
  { name: 'a state management issue', fixes: ['with improved state management', 'with improved checks'] },
  { name: 'an authentication issue', fixes: ['with improved authentication checks', 'with stricter verification'] },
];

module.exports = { subjectTemplates, pool, securityComponents, securityClasses };
