// Writes www/js/config.js from environment variables so the API key is never committed.
//   GEMINI_API_KEY=... npm run config
// Also reads bfdi-talk/.env if present (KEY=value lines).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envFile = join(root, '.env');
const env = { ...process.env };
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !env[m[1]]) env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  }
}
const config = { GEMINI_API_KEY: env.GEMINI_API_KEY || '' };
writeFileSync(join(root, 'www', 'js', 'config.js'),
  `// Generated by scripts/write-config.mjs — do not commit.\nexport default ${JSON.stringify(config, null, 2)};\n`);
console.log(`www/js/config.js written (${config.GEMINI_API_KEY ? 'with' : 'WITHOUT'} a built-in Gemini API key)`);
