// Writes www/js/config.js from environment variables so the API key is never committed,
// and copies the Supabase client into www/vendor/.
//   GEMINI_API_KEY=... SUPABASE_URL=... SUPABASE_ANON_KEY=... npm run config
// Also reads bfdi-talk/.env if present (KEY=value lines).
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envFile = join(root, '.env');
const env = { ...process.env };
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !env[m[1]]) env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  }
}
const config = {
  GEMINI_API_KEY: env.GEMINI_API_KEY || '',
  // Accounts + plans. The anon/publishable key is meant to be public (row-level security protects the data).
  SUPABASE_URL: env.SUPABASE_URL || '',
  SUPABASE_ANON_KEY: env.SUPABASE_ANON_KEY || '',
};
writeFileSync(join(root, 'www', 'js', 'config.js'),
  `// Generated by scripts/write-config.mjs — do not commit.\nexport default ${JSON.stringify(config, null, 2)};\n`);
mkdirSync(join(root, 'www', 'vendor'), { recursive: true });
copyFileSync(join(root, 'node_modules', '@supabase', 'supabase-js', 'dist', 'umd', 'supabase.js'), join(root, 'www', 'vendor', 'supabase.js'));
console.log(`www/js/config.js written (${config.GEMINI_API_KEY ? 'with' : 'WITHOUT'} a built-in Gemini API key, accounts ${config.SUPABASE_URL ? 'ON' : 'OFF'})`);
