"""Writes the apps' offline copy of the plans and agents:

    python -m hubcloud.export_config
"""

import json
import os

from . import config

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "app", "src", "main",
                   "assets", "www", "js", "cloud-config.js")


def render():
    return ("// Generated by `python -m hubcloud.export_config` from hubcloud/config.py.\n"
            "// The apps use it until they have fetched /v1/config. Do not edit.\n"
            "window.HUB_CLOUD_CONFIG=" + json.dumps(config.public_config(), sort_keys=True) + ";\n")


if __name__ == "__main__":
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(render())
    print("wrote", os.path.relpath(OUT))
